-- Run once in Snowsight as ACCOUNTADMIN when the API logs
-- "Unknown user-defined function PIP.APP.PIP_FIRST_STEP_MINUTES".
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PIP_WH;
USE SCHEMA PIP.APP;

CREATE OR REPLACE FUNCTION PIP.APP.PIP_EXTRACT_JSON(S VARCHAR)
RETURNS VARIANT
AS
$$
  CASE
    WHEN S IS NULL THEN NULL
    WHEN POSITION('{', S) = 0 OR POSITION('}', REVERSE(S)) = 0 THEN NULL
    WHEN (LENGTH(S) - POSITION('}', REVERSE(S)) + 1) < POSITION('{', S) THEN NULL
    ELSE TRY_PARSE_JSON(SUBSTR(S, POSITION('{', S), (LENGTH(S) - POSITION('}', REVERSE(S)) + 1) - POSITION('{', S) + 1))
  END
$$;

CREATE OR REPLACE FUNCTION PIP.APP.PIP_FIRST_STEP_MINUTES(CATEGORY VARCHAR, EST_MINUTES NUMBER)
RETURNS NUMBER
AS
$$
  CASE
    WHEN CATEGORY IN ('assignment', 'work', 'class') THEN LEAST(COALESCE(EST_MINUTES, 60), 20)
    ELSE COALESCE(EST_MINUTES, 15)
  END
$$;

CREATE OR REPLACE FUNCTION PIP.APP.PIP_DECAY_COST(
  CURVE VARCHAR, FLOOR_WEIGHT FLOAT, HALF_LIFE_HOURS FLOAT,
  HOURS_TO_DUE FLOAT, HOURS_OPEN FLOAT, DEFER_COUNT FLOAT, T FLOAT)
RETURNS FLOAT
AS
$$
  GREATEST(0.0, LEAST(1.0,
    CASE
      WHEN CURVE = 'cliff' AND HOURS_TO_DUE IS NOT NULL THEN
        IFF(HOURS_TO_DUE <= 0 OR T >= HOURS_TO_DUE, 1.0,
            FLOOR_WEIGHT + (0.5 - FLOOR_WEIGHT) * DIV0(T, HOURS_TO_DUE))
      WHEN CURVE = 'daily_reset' THEN
        FLOOR_WEIGHT + (1 - FLOOR_WEIGHT) * (MOD(GREATEST(COALESCE(HOURS_OPEN, 0), 0) + T, 24) / 24)
      WHEN CURVE = 'rising_floor' THEN
        FLOOR_WEIGHT + DIV0(GREATEST(COALESCE(HOURS_OPEN, 0), 0) + T,
                            2 * IFF(HALF_LIFE_HOURS > 0, HALF_LIFE_HOURS, 1))
      WHEN CURVE = 'defer_multiplier' THEN
        (FLOOR_WEIGHT + DIV0(T, 2 * IFF(HALF_LIFE_HOURS > 0, HALF_LIFE_HOURS, 1)))
          * (1 + 0.5 * COALESCE(DEFER_COUNT, 0))
      ELSE
        FLOOR_WEIGHT + DIV0(T, 2 * IFF(HALF_LIFE_HOURS > 0, HALF_LIFE_HOURS, 1))
    END))
$$;

CREATE OR REPLACE FUNCTION PIP.APP.PIP_FMT_TIME(TS TIMESTAMP_NTZ)
RETURNS VARCHAR
AS
$$
  IFF(MOD(HOUR(TS), 12) = 0, 12, MOD(HOUR(TS), 12))::VARCHAR
    || ':' || LPAD(MINUTE(TS)::VARCHAR, 2, '0')
    || IFF(HOUR(TS) < 12, ' AM', ' PM')
$$;

GRANT USAGE ON FUNCTION PIP.APP.PIP_EXTRACT_JSON(VARCHAR) TO ROLE PIP_API_ROLE;
GRANT USAGE ON FUNCTION PIP.APP.PIP_FIRST_STEP_MINUTES(VARCHAR, NUMBER) TO ROLE PIP_API_ROLE;
GRANT USAGE ON FUNCTION PIP.APP.PIP_DECAY_COST(VARCHAR, FLOAT, FLOAT, FLOAT, FLOAT, FLOAT, FLOAT) TO ROLE PIP_API_ROLE;
GRANT USAGE ON FUNCTION PIP.APP.PIP_FMT_TIME(TIMESTAMP_NTZ) TO ROLE PIP_API_ROLE;

SHOW USER FUNCTIONS LIKE 'PIP_%' IN SCHEMA PIP.APP;
