-- =============================================================================
-- Pip / Snowflake layer  --  03_functions.sql
-- GENERATED by snowflake/build.mjs from snowflake/src/*. Edit the sources and
-- run `node snowflake/build.mjs`; do not hand-edit this file.
--
-- Contents
--   (a) Cortex verification block  -> CORTEX_CONFIG
--   (b) SQL helper UDFs: PIP_EXTRACT_JSON, PIP_FIRST_STEP_MINUTES, PIP_DECAY_COST, PIP_FMT_TIME
--   (c) Cortex call chain (a JavaScript helper inlined in each procedure; it reads
--       CORTEX_CONFIG, then walks AI_COMPLETE -> SNOWFLAKE.CORTEX.COMPLETE over
--       claude-sonnet-4-5 -> mistral-large2 -> llama3.1-8b with try/catch per attempt)
--   (d) EXTRACT_FROM_TRANSCRIPT(CAPTURE_ID)
--   (e) BUILD_PLAN(STUDENT_ID, CAPTURE_ID, EXTRA_CONTEXT)
--   (f) RECORD_ACTION(STUDENT_ID, PLAN_ID, TASK_ID, KIND)
--
-- The procedures are LANGUAGE JAVASCRIPT + EXECUTE AS CALLER: the caller's Cortex
-- privileges and session TIMEZONE apply, every SQL statement uses bind variables,
-- and each Cortex attempt is isolated in try/catch (a missing function only fails
-- that attempt). The pre-rank itself is one SQL query using the UDFs below.
-- =============================================================================

USE WAREHOUSE PIP_WH;
USE SCHEMA PIP.APP;

-- -----------------------------------------------------------------------------
-- (a) Cortex verification. Tries each function/model with a trivial prompt; the
-- first success wins. Result is MERGEd into CORTEX_CONFIG and returned.
-- AI_TRANSCRIBE is probed with a file that does not exist: "unknown function"
-- means unavailable, any other error (file not found, etc.) means the function
-- exists. The API /health?refresh=1 does the definitive check with a real m4a.
-- -----------------------------------------------------------------------------
EXECUTE IMMEDIATE
$$
DECLARE
  v_complete_fn    VARCHAR DEFAULT NULL;
  v_complete_model VARCHAR DEFAULT NULL;
  v_embed_fn       VARCHAR DEFAULT NULL;
  v_transcribe_fn  VARCHAR DEFAULT NULL;
  v_fn             VARCHAR;
  v_model          VARCHAR;
  v_sql            VARCHAR;
  v_msg            VARCHAR;
  v_errors         VARCHAR DEFAULT '';
BEGIN
  -- completion: AI_COMPLETE x 3 models, then SNOWFLAKE.CORTEX.COMPLETE x 3 models
  FOR i IN 0 TO 5 DO
    IF (v_complete_fn IS NULL) THEN
      IF (i < 3) THEN
        v_fn := 'AI_COMPLETE';
      ELSE
        v_fn := 'SNOWFLAKE.CORTEX.COMPLETE';
      END IF;
      IF (i = 0 OR i = 3) THEN
        v_model := 'claude-sonnet-4-5';
      ELSEIF (i = 1 OR i = 4) THEN
        v_model := 'mistral-large2';
      ELSE
        v_model := 'llama3.1-8b';
      END IF;
      v_sql := 'SELECT ' || v_fn || '(''' || v_model || ''', ''Reply with the single word OK.'')';
      BEGIN
        EXECUTE IMMEDIATE :v_sql;
        v_complete_fn := v_fn;
        v_complete_model := v_model;
      EXCEPTION
        WHEN OTHER THEN
          v_msg := SQLERRM;
          v_errors := v_errors || v_fn || '/' || v_model || ': ' || LEFT(v_msg, 200) || ' | ';
      END;
    END IF;
  END FOR;

  -- embeddings
  BEGIN
    EXECUTE IMMEDIATE 'SELECT AI_EMBED(''snowflake-arctic-embed-m-v1.5'', ''hello'')';
    v_embed_fn := 'AI_EMBED';
  EXCEPTION
    WHEN OTHER THEN
      v_msg := SQLERRM;
      v_errors := v_errors || 'AI_EMBED: ' || LEFT(v_msg, 200) || ' | ';
  END;
  IF (v_embed_fn IS NULL) THEN
    BEGIN
      EXECUTE IMMEDIATE 'SELECT SNOWFLAKE.CORTEX.EMBED_TEXT_768(''snowflake-arctic-embed-m-v1.5'', ''hello'')';
      v_embed_fn := 'SNOWFLAKE.CORTEX.EMBED_TEXT_768';
    EXCEPTION
      WHEN OTHER THEN
        v_msg := SQLERRM;
        v_errors := v_errors || 'EMBED_TEXT_768: ' || LEFT(v_msg, 200) || ' | ';
    END;
  END IF;

  -- transcription probe (a success is not expected: the file does not exist)
  BEGIN
    EXECUTE IMMEDIATE 'SELECT AI_TRANSCRIBE(TO_FILE(''@PIP.APP.AUDIO_STAGE'', ''pip_verify/does_not_exist.m4a''))';
    v_transcribe_fn := 'AI_TRANSCRIBE';
  EXCEPTION
    WHEN OTHER THEN
      v_msg := SQLERRM;
      IF (v_msg ILIKE '%unknown function%' OR v_msg ILIKE '%unknown user-defined function%' OR v_msg ILIKE '%invalid identifier%') THEN
        v_transcribe_fn := NULL;
        v_errors := v_errors || 'AI_TRANSCRIBE: ' || LEFT(v_msg, 200) || ' | ';
      ELSE
        v_transcribe_fn := 'AI_TRANSCRIBE';
      END IF;
  END;

  MERGE INTO PIP.APP.CORTEX_CONFIG t
  USING (
    SELECT 'complete_fn' AS cfg_key, :v_complete_fn AS cfg_value
    UNION ALL SELECT 'complete_model', :v_complete_model
    UNION ALL SELECT 'embed_fn', :v_embed_fn
    UNION ALL SELECT 'transcribe_fn', :v_transcribe_fn
  ) s
  ON t.key = s.cfg_key
  WHEN MATCHED THEN UPDATE SET value = s.cfg_value, verified_at = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
  WHEN NOT MATCHED THEN INSERT (key, value, verified_at)
    VALUES (s.cfg_key, s.cfg_value, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ);

  RETURN OBJECT_CONSTRUCT_KEEP_NULL(
    'complete_fn', v_complete_fn,
    'complete_model', v_complete_model,
    'embed_fn', v_embed_fn,
    'transcribe_fn', v_transcribe_fn,
    'errors', v_errors);
END;
$$;

SELECT * FROM PIP.APP.CORTEX_CONFIG ORDER BY key;

-- -----------------------------------------------------------------------------
-- (b) Helper UDFs
-- -----------------------------------------------------------------------------

-- LLM text -> JSON object. Code fences and prose are dropped by slicing from the
-- first '{' to the last '}'; returns NULL when nothing parses.
CREATE OR REPLACE FUNCTION PIP.APP.PIP_EXTRACT_JSON(S VARCHAR)
RETURNS VARIANT
AS
$$
  CASE
    WHEN S IS NULL THEN NULL
    WHEN POSITION('{', S) = 0 OR POSITION('}', REVERSE(S)) = 0 THEN NULL
    WHEN (LENGTH(S) - POSITION('}', REVERSE(S)) + 1) < POSITION('{', S) THEN NULL
    ELSE TRY_PARSE_JSON(
      SUBSTR(S, POSITION('{', S), (LENGTH(S) - POSITION('}', REVERSE(S)) + 1) - POSITION('{', S) + 1))
  END
$$;

-- Minutes of the first useful step (CONTRACT section 4).
CREATE OR REPLACE FUNCTION PIP.APP.PIP_FIRST_STEP_MINUTES(CATEGORY VARCHAR, EST_MINUTES NUMBER)
RETURNS NUMBER
AS
$$
  CASE
    WHEN CATEGORY IN ('assignment', 'work', 'class') THEN LEAST(COALESCE(EST_MINUTES, 60), 20)
    ELSE COALESCE(EST_MINUTES, 15)
  END
$$;

-- Relative cost (0..1) of postponing a task by T hours (CONTRACT section 4 curves).
-- HOURS_TO_DUE is NULL for undated tasks (cliff then falls back to linear).
CREATE OR REPLACE FUNCTION PIP.APP.PIP_DECAY_COST(
  CURVE VARCHAR, FLOOR_WEIGHT FLOAT, HALF_LIFE_HOURS FLOAT,
  HOURS_TO_DUE FLOAT, HOURS_OPEN FLOAT, DEFER_COUNT FLOAT, T FLOAT)
RETURNS FLOAT
AS
$$
  CASE
    WHEN CURVE = 'cliff' AND HOURS_TO_DUE IS NOT NULL THEN
      IFF(T >= HOURS_TO_DUE, 1.0, FLOOR_WEIGHT + (0.5 - FLOOR_WEIGHT) * DIV0(T, HOURS_TO_DUE))
    WHEN CURVE = 'daily_reset' THEN
      FLOOR_WEIGHT + (1 - FLOOR_WEIGHT) * (MOD(COALESCE(HOURS_OPEN, 0) + T, 24) / 24)
    WHEN CURVE = 'rising_floor' THEN
      LEAST(1.0, FLOOR_WEIGHT + DIV0(COALESCE(HOURS_OPEN, 0) + T, 2 * HALF_LIFE_HOURS))
    WHEN CURVE = 'defer_multiplier' THEN
      LEAST(1.0, (FLOOR_WEIGHT + DIV0(T, 2 * HALF_LIFE_HOURS)) * (1 + 0.5 * COALESCE(DEFER_COUNT, 0)))
    ELSE
      LEAST(1.0, FLOOR_WEIGHT + DIV0(T, 2 * HALF_LIFE_HOURS))
  END
$$;

-- TIMESTAMP_NTZ -> '2:00 PM'
CREATE OR REPLACE FUNCTION PIP.APP.PIP_FMT_TIME(TS TIMESTAMP_NTZ)
RETURNS VARCHAR
AS
$$
  IFF(MOD(HOUR(TS), 12) = 0, 12, MOD(HOUR(TS), 12))::VARCHAR
    || ':' || LPAD(MINUTE(TS)::VARCHAR, 2, '0')
    || IFF(HOUR(TS) < 12, ' AM', ' PM')
$$;

-- -----------------------------------------------------------------------------
-- (d) EXTRACT_FROM_TRANSCRIPT
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PIP.APP.EXTRACT_FROM_TRANSCRIPT(CAPTURE_ID VARCHAR)
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
// ===== common.js =====
// ---------------------------------------------------------------------------
// Shared helpers, inlined by build.mjs at the top of every JavaScript procedure.
// ES5 only (var/function), no template literals, never two dollar signs in a row.
// Times are handled as "naive" wall-clock values: a 'YYYY-MM-DDTHH:MI:SS' string
// is mapped to Date.UTC(...) milliseconds and formatted back with getUTC*, so the
// JavaScript engine's own time zone never matters.
// ---------------------------------------------------------------------------
var PIP_TS_FMT = "'YYYY-MM-DD\"T\"HH24:MI:SS'";
var PIP_CATEGORIES = ['class', 'assignment', 'errand', 'meal', 'money', 'work', 'club', 'social', 'rest'];
var PIP_CONSTRAINT_KINDS = ['time_window', 'cash', 'fixed_block', 'travel'];
var PIP_RULE_IDS = ['irreversible_loss', 'fixed_block_collision', 'basic_needs', 'fits_window', 'academic_deadline'];
var PIP_MODELS = ['claude-sonnet-4-5', 'mistral-large2', 'llama3.1-8b'];
var PIP_COMPLETE_FNS = ['AI_COMPLETE', 'SNOWFLAKE.CORTEX.COMPLETE'];
var PIP_DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
var PIP_DAY_LONG = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
var PIP_MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
var PIP_LAST_OK = null;

function pipIn(arr, v) {
  for (var i = 0; i < arr.length; i++) { if (arr[i] === v) { return true; } }
  return false;
}
function pipIsNil(v) { return v === null || v === undefined; }
function pipStr(v) { return pipIsNil(v) ? '' : String(v); }
function pipNum(v) {
  if (pipIsNil(v) || v === '' || typeof v === 'boolean') { return null; }
  var n = Number(v);
  return isFinite(n) ? n : null;
}
function pipP2(n) { return (n < 10 ? '0' : '') + n; }
function pipTrim(s) { return pipStr(s).replace(/^\s+|\s+$/g, ''); }

// ----- SQL ------------------------------------------------------------------
function pipExec(sql, binds) {
  return snowflake.execute({ sqlText: sql, binds: binds || [] });
}
// cols: upper-case column names/aliases to read from each row
function pipRows(sql, binds, cols) {
  var rs = pipExec(sql, binds);
  var out = [];
  while (rs.next()) {
    var row = {};
    for (var i = 0; i < cols.length; i++) {
      var v = rs.getColumnValue(cols[i]);
      row[cols[i]] = (v === undefined) ? null : v;
    }
    out.push(row);
  }
  return out;
}
function pipScalar(sql, binds) {
  var rs = pipExec(sql, binds);
  if (rs.next()) {
    var v = rs.getColumnValue(1);
    return (v === undefined) ? null : v;
  }
  return null;
}
function pipUuid() { return String(pipScalar('SELECT UUID_STRING()', [])); }
function pipNowLocal() {
  return String(pipScalar('SELECT TO_VARCHAR(CURRENT_TIMESTAMP()::TIMESTAMP_NTZ, ' + PIP_TS_FMT + ')', []));
}

// ----- time -----------------------------------------------------------------
// 'YYYY-MM-DDTHH:MI[:SS]' (or with a space) -> naive ms, else null
function pipParseTs(s) {
  var m = /^(\d{4})-(\d{2})-(\d{2})[T ](\d{1,2}):(\d{2})(?::(\d{2}))?/.exec(pipTrim(s));
  if (!m) { return null; }
  var h = Number(m[4]); var mi = Number(m[5]); var se = Number(m[6] || 0);
  if (h > 23 || mi > 59 || se > 59) { return null; }
  return Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]), h, mi, se);
}
function pipParseDate(s) {
  var m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(pipTrim(s));
  if (!m) { return null; }
  return Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
}
// 'H:MM' / 'HH:MM[:SS]' -> minutes of day, else null
function pipParseHm(s) {
  var m = /^(\d{1,2}):(\d{2})(?::\d{2})?$/.exec(pipTrim(s));
  if (!m) { return null; }
  var h = Number(m[1]); var mi = Number(m[2]);
  if (h > 23 || mi > 59) { return null; }
  return h * 60 + mi;
}
function pipFmtTs(ms) {
  var d = new Date(ms);
  return d.getUTCFullYear() + '-' + pipP2(d.getUTCMonth() + 1) + '-' + pipP2(d.getUTCDate()) + 'T' +
    pipP2(d.getUTCHours()) + ':' + pipP2(d.getUTCMinutes()) + ':' + pipP2(d.getUTCSeconds());
}
function pipFmtDate(ms) { return pipFmtTs(ms).substring(0, 10); }
function pipFmtHmOfDay(min) { return pipP2(Math.floor(min / 60)) + ':' + pipP2(min % 60); }
function pipDayStart(ms) { var d = new Date(ms); return Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()); }
function pipIsoDow(ms) { var d = new Date(ms).getUTCDay(); return d === 0 ? 7 : d; }
// '2:00 PM'
function pipClock(ms) {
  var d = new Date(ms); var h = d.getUTCHours(); var h12 = h % 12 === 0 ? 12 : h % 12;
  return h12 + ':' + pipP2(d.getUTCMinutes()) + (h < 12 ? ' AM' : ' PM');
}
// 'Fri Sep 18'
function pipDayLabel(ms) {
  var d = new Date(ms);
  return PIP_DAY_NAMES[d.getUTCDay()] + ' ' + PIP_MONTHS[d.getUTCMonth()] + ' ' + d.getUTCDate();
}
function pipDaysBetween(fromMs, toMs) { return Math.round((pipDayStart(toMs) - pipDayStart(fromMs)) / 86400000); }
// 'at 5:00 PM today' | 'tomorrow at 11:59 PM' | 'Fri Sep 18 at 5:00 PM'
function pipDueDesc(dueMs, nowMs) {
  var days = pipDaysBetween(nowMs, dueMs);
  if (days === 0) { return 'at ' + pipClock(dueMs) + ' today'; }
  if (days === 1) { return 'tomorrow at ' + pipClock(dueMs); }
  return pipDayLabel(dueMs) + ' at ' + pipClock(dueMs);
}
// '$79' | '$7.50'
function pipMoney(x) {
  var n = Number(x);
  if (Math.abs(n - Math.round(n)) < 0.005) { return '$' + Math.round(n); }
  return '$' + n.toFixed(2);
}
function pipPlural(n, word) { return n + ' ' + word + (n === 1 ? '' : 's'); }

// ----- LLM output -------------------------------------------------------------
// Drops code fences / prose by slicing first '{' .. last '}' (same idea as PIP_EXTRACT_JSON).
function pipExtractJson(text) {
  if (pipIsNil(text)) { return null; }
  var s = String(text);
  var a = s.indexOf('{'); var b = s.lastIndexOf('}');
  if (a < 0 || b <= a) { return null; }
  try {
    var o = JSON.parse(s.substring(a, b + 1));
    return (o && typeof o === 'object' && !(o instanceof Array)) ? o : null;
  } catch (e) {
    return null;
  }
}
// first sentence only; '' when not a usable string
function pipOneSentence(s) {
  if (typeof s !== 'string') { return ''; }
  var t = pipTrim(s.replace(/\s+/g, ' '));
  var m = /^(.+?[.!?])\s+[A-Z]/.exec(t);
  if (m) { t = m[1]; }
  if (t.length > 320) { t = t.substring(0, 317) + '...'; }
  return t;
}

// ----- Cortex -------------------------------------------------------------------
function pipCortexConfig() {
  var cfg = {};
  try {
    var rows = pipRows('SELECT key AS CFG_KEY, value AS CFG_VALUE FROM PIP.APP.CORTEX_CONFIG', [], ['CFG_KEY', 'CFG_VALUE']);
    for (var i = 0; i < rows.length; i++) { cfg[String(rows[i].CFG_KEY)] = rows[i].CFG_VALUE; }
  } catch (e) {
    cfg = {};
  }
  return cfg;
}
// One completion. Walks the fallback chain; returns {text, fn, model, errors}.
function pipComplete(prompt) {
  var cfg = pipCortexConfig();
  var order = [];
  var errors = [];
  function add(fn, model) {
    if (!pipIn(PIP_COMPLETE_FNS, fn)) { return; }
    if (typeof model !== 'string' || !/^[a-z0-9][a-z0-9.\-]*$/.test(model)) { return; }
    for (var k = 0; k < order.length; k++) {
      if (order[k].fn === fn && order[k].model === model) { return; }
    }
    order.push({ fn: fn, model: model });
  }
  if (PIP_LAST_OK) { add(PIP_LAST_OK.fn, PIP_LAST_OK.model); }
  add(cfg.complete_fn || 'AI_COMPLETE', cfg.complete_model || 'claude-sonnet-4-5');
  for (var f = 0; f < PIP_COMPLETE_FNS.length; f++) {
    for (var m = 0; m < PIP_MODELS.length; m++) { add(PIP_COMPLETE_FNS[f], PIP_MODELS[m]); }
  }
  for (var i = 0; i < order.length; i++) {
    var a = order[i];
    try {
      var rs = pipExec('SELECT ' + a.fn + "('" + a.model + "', ?) AS OUT_TEXT", [prompt]);
      if (rs.next()) {
        var v = rs.getColumnValue('OUT_TEXT');
        if (!pipIsNil(v)) {
          PIP_LAST_OK = a;
          return { text: (typeof v === 'string') ? v : JSON.stringify(v), fn: a.fn, model: a.model, errors: errors };
        }
      }
      errors.push(a.fn + '/' + a.model + ': empty response');
    } catch (e) {
      errors.push(a.fn + '/' + a.model + ': ' + String((e && e.message) || e).substring(0, 200));
    }
  }
  return { text: null, fn: null, model: null, errors: errors };
}
// Completion + JSON parse, retried once. Returns {obj, fn, model, attempts, errors}.
function pipCompleteJson(prompt) {
  var errors = [];
  var p = prompt;
  for (var k = 1; k <= 2; k++) {
    var r = pipComplete(p);
    errors = errors.concat(r.errors);
    if (r.text !== null) {
      var obj = pipExtractJson(r.text);
      if (obj) { return { obj: obj, fn: r.fn, model: r.model, attempts: k, errors: errors }; }
      errors.push('attempt ' + k + ': ' + r.model + ' did not return parseable JSON');
    }
    p = prompt + '\n\nIMPORTANT: your previous reply was not valid JSON. Reply with ONLY the JSON object, starting with { and ending with }.';
  }
  return { obj: null, fn: null, model: null, attempts: 2, errors: errors };
}

// ----- rows -----------------------------------------------------------------------
var PIP_TASK_COLS = ['TASK_ID', 'STUDENT_ID', 'CAPTURE_ID', 'RAW_TEXT', 'NORMALIZED_TEXT', 'CATEGORY', 'DUE_S',
  'MONEY', 'EST', 'STATUS', 'DEFERS', 'CREATED_S'];
var PIP_TASK_SELECT = 'SELECT task_id AS TASK_ID, student_id AS STUDENT_ID, capture_id AS CAPTURE_ID, ' +
  'raw_text AS RAW_TEXT, normalized_text AS NORMALIZED_TEXT, category AS CATEGORY, ' +
  'TO_VARCHAR(due_at, ' + PIP_TS_FMT + ') AS DUE_S, money_at_risk::FLOAT AS MONEY, est_minutes::FLOAT AS EST, ' +
  'status AS STATUS, defer_count::FLOAT AS DEFERS, TO_VARCHAR(created_at, ' + PIP_TS_FMT + ') AS CREATED_S ' +
  'FROM PIP.APP.TASKS ';
// Task (types.ts) from a PIP_TASK_SELECT row
function pipTaskJson(r) {
  return {
    task_id: String(r.TASK_ID),
    student_id: String(r.STUDENT_ID),
    capture_id: pipIsNil(r.CAPTURE_ID) ? null : String(r.CAPTURE_ID),
    raw_text: pipStr(r.RAW_TEXT),
    normalized_text: pipStr(r.NORMALIZED_TEXT),
    category: pipStr(r.CATEGORY),
    due_at: pipIsNil(r.DUE_S) ? null : String(r.DUE_S),
    money_at_risk: pipNum(r.MONEY),
    est_minutes: pipNum(r.EST),
    status: pipStr(r.STATUS),
    defer_count: pipNum(r.DEFERS) || 0,
    created_at: pipStr(r.CREATED_S)
  };
}
function pipLoadTask(taskId) {
  var rows = pipRows(PIP_TASK_SELECT + 'WHERE task_id = ?', [taskId], PIP_TASK_COLS);
  return rows.length ? pipTaskJson(rows[0]) : null;
}

// ===== extract.js =====
// ---------------------------------------------------------------------------
// EXTRACT_FROM_TRANSCRIPT(CAPTURE_ID VARCHAR) RETURNS VARIANT
// {tasks: Task[], constraints: Constraint[], model, attempts[, error]}
// ---------------------------------------------------------------------------
function pipCleanTs(v) {
  var ms = pipParseTs(v);
  return ms === null ? null : pipFmtTs(ms);
}
function pipCleanConstraint(c) {
  if (!c || typeof c !== 'object') { return null; }
  var kind = pipTrim(c.kind);
  var v = (c.value && typeof c.value === 'object') ? c.value : {};
  if (kind === 'fixed_block') {
    var s = pipParseHm(v.starts_at);
    if (s === null) { return null; }
    var e = pipParseHm(v.ends_at);
    return { kind: kind, value: {
      title: pipTrim(v.title) || 'Class',
      starts_at: pipFmtHmOfDay(s),
      ends_at: e === null ? null : pipFmtHmOfDay(e),
      location: pipTrim(v.location) || null
    } };
  }
  if (kind === 'cash') {
    var amount = pipNum(v.amount);
    if (amount === null || amount < 0) { return null; }
    var until = pipParseDate(v.until);
    return { kind: kind, value: { amount: Math.round(amount * 100) / 100, until: until === null ? null : pipFmtDate(until) } };
  }
  if (kind === 'time_window') {
    var minutes = pipNum(v.minutes);
    if (minutes === null || minutes <= 0) { return null; }
    return { kind: kind, value: { minutes: Math.round(minutes) } };
  }
  if (kind === 'travel') {
    var tm = pipNum(v.minutes);
    if (tm === null || tm <= 0) { return null; }
    return { kind: kind, value: { minutes: Math.round(tm), to: pipTrim(v.to) || null } };
  }
  return null;
}

function pipExtractPrompt(transcript, nowStr, openTasks, profile) {
  var nowMs = pipParseTs(nowStr);
  var today = pipDayStart(nowMs);
  var days = [];
  for (var k = 1; k <= 7; k++) {
    var d = today + k * 86400000;
    days.push(PIP_DAY_LONG[new Date(d).getUTCDay()] + ' = ' + pipFmtDate(d));
  }
  var taskLines = [];
  for (var i = 0; i < openTasks.length; i++) {
    taskLines.push('  - id "' + openTasks[i].id + '" | ' + openTasks[i].category + ' | ' + openTasks[i].text);
  }
  return [
    'You extract tasks and constraints for Pip, a day planner for a first-time independent university student.',
    'Reply with ONLY one JSON object (no prose, no code fences) with exactly this shape:',
    '{"tasks":[{"raw_text":"...","normalized_text":"...","category":"...","due_at":"YYYY-MM-DDTHH:MI:SS or null","money_at_risk":0,"est_minutes":0,"existing_task_id":"id or null"}],"constraints":[{"kind":"...","value":{}}]}',
    '',
    'Rules:',
    '- category is exactly one of: class, assignment, errand, meal, money, work, club, social, rest.',
    '- raw_text is the student\'s own words for that task; normalized_text is a short imperative phrase such as "Return headphones for refund".',
    '- Now is ' + nowStr + ' (' + PIP_DAY_LONG[new Date(nowMs).getUTCDay()] + '). Today is ' + pipFmtDate(today) + '; tomorrow is ' + pipFmtDate(today + 86400000) + '.',
    '- A weekday name means the next such day strictly after today: ' + days.join(', ') + '.',
    '- Write every deadline as local time "YYYY-MM-DDTHH:MI:SS". A bare time such as "5 PM" means today at 17:00:00. "Due tomorrow" without a time means tomorrow at 23:59:00. No deadline mentioned means null.',
    '- money_at_risk is the dollars lost if the deadline is missed (refund, fee, fine), otherwise null. est_minutes is a realistic whole-minute estimate, or null.',
    '- A class, lab, lecture, shift or appointment at a fixed time is NOT a task. Output it as a constraint {"kind":"fixed_block","value":{"title":"...","starts_at":"HH:MM","ends_at":"HH:MM or null","location":"... or null"}} with 24-hour times.',
    '- "$X until <day>" is a constraint {"kind":"cash","value":{"amount":X,"until":"YYYY-MM-DD"}}.',
    '- "I only have N minutes" is a constraint {"kind":"time_window","value":{"minutes":N}}; half an hour = 30, an hour = 60.',
    '- Travel time ("20 minutes to get to campus") is a constraint {"kind":"travel","value":{"minutes":N,"to":"..."}}.',
    '- The student already has these open tasks. If the transcript mentions one of them again, set existing_task_id to its id and keep its category; otherwise existing_task_id is null.',
    taskLines.length ? taskLines.join('\n') : '  (none)',
    '- Questions such as "What should I do?" are not tasks. Never invent anything that was not said.',
    '- Current cash on file: ' + pipMoney(profile.cash) + '.',
    '- If nothing is found reply {"tasks":[],"constraints":[]}.',
    '',
    'Transcript:',
    '"""' + transcript + '"""'
  ].join('\n');
}

function pipExtractMain(captureId) {
  var caps = pipRows('SELECT student_id AS STUDENT_ID, transcript AS TRANSCRIPT FROM PIP.APP.CAPTURES WHERE capture_id = ?',
    [pipStr(captureId)], ['STUDENT_ID', 'TRANSCRIPT']);
  if (!caps.length) {
    return { tasks: [], constraints: [], model: null, attempts: 0, error: 'capture not found: ' + pipStr(captureId) };
  }
  var studentId = String(caps[0].STUDENT_ID);
  var transcript = pipStr(caps[0].TRANSCRIPT);
  var nowStr = pipNowLocal();

  var openRows = pipRows("SELECT task_id AS TASK_ID, category AS CATEGORY, normalized_text AS NORMALIZED_TEXT FROM PIP.APP.TASKS " +
    "WHERE student_id = ? AND status IN ('open', 'deferred') ORDER BY created_at", [studentId], ['TASK_ID', 'CATEGORY', 'NORMALIZED_TEXT']);
  var openTasks = [];
  var openIds = {};
  for (var i = 0; i < openRows.length; i++) {
    openTasks.push({ id: String(openRows[i].TASK_ID), category: pipStr(openRows[i].CATEGORY), text: pipStr(openRows[i].NORMALIZED_TEXT) });
    openIds[String(openRows[i].TASK_ID)] = pipStr(openRows[i].CATEGORY);
  }
  var profRows = pipRows('SELECT cash_available::FLOAT AS CASH FROM PIP.APP.PROFILE WHERE student_id = ?', [studentId], ['CASH']);
  var profile = { cash: profRows.length ? (pipNum(profRows[0].CASH) || 0) : 0 };

  var llm = pipCompleteJson(pipExtractPrompt(transcript, nowStr, openTasks, profile));
  if (!llm.obj) {
    return { tasks: [], constraints: [], model: null, attempts: 2, error: 'LLM extraction failed: ' + llm.errors.join(' | ') };
  }

  var touched = [];
  var rawTasks = (llm.obj.tasks instanceof Array) ? llm.obj.tasks : [];
  for (var t = 0; t < rawTasks.length && t < 20; t++) {
    var x = rawTasks[t];
    if (!x || typeof x !== 'object') { continue; }
    var raw = pipTrim(x.raw_text);
    var norm = pipTrim(x.normalized_text) || raw;
    if (!raw) { raw = norm; }
    if (!norm) { continue; }
    if (norm.length > 200) { norm = norm.substring(0, 200); }
    var category = pipIn(PIP_CATEGORIES, pipTrim(x.category)) ? pipTrim(x.category) : 'errand';
    var due = pipCleanTs(x.due_at);
    var money = pipNum(x.money_at_risk);
    money = (money !== null && money > 0) ? String(Math.round(money * 100) / 100) : '';
    var est = pipNum(x.est_minutes);
    est = (est !== null && est > 0) ? String(Math.round(est)) : '';
    var existing = pipTrim(x.existing_task_id);
    var targetId = (existing && openIds.hasOwnProperty(existing)) ? existing : null;

    if (!targetId) {
      var sim = pipRows("SELECT task_id AS TASK_ID FROM PIP.APP.TASKS WHERE student_id = ? AND status IN ('open', 'deferred') " +
        'AND category = ? AND JAROWINKLER_SIMILARITY(LOWER(normalized_text), LOWER(?)) >= 80 ' +
        'ORDER BY JAROWINKLER_SIMILARITY(LOWER(normalized_text), LOWER(?)) DESC, created_at LIMIT 1',
        [studentId, category, norm, norm], ['TASK_ID']);
      if (sim.length) { targetId = String(sim[0].TASK_ID); }
    }

    if (targetId) {
      pipExec('UPDATE PIP.APP.TASKS SET ' +
        'due_at = COALESCE(TRY_TO_TIMESTAMP_NTZ(NULLIF(?, \'\'), ' + PIP_TS_FMT + '), due_at), ' +
        'money_at_risk = COALESCE(TRY_TO_NUMBER(NULLIF(?, \'\'), 10, 2), money_at_risk), ' +
        'est_minutes = COALESCE(TRY_TO_NUMBER(NULLIF(?, \'\')), est_minutes), ' +
        "capture_id = ?, status = 'open' " +
        'WHERE task_id = ? AND student_id = ?',
        [due || '', money, est, String(captureId), targetId, studentId]);
    } else {
      targetId = pipUuid();
      pipExec('INSERT INTO PIP.APP.TASKS (task_id, student_id, capture_id, raw_text, normalized_text, category, due_at, ' +
        'money_at_risk, est_minutes, status, defer_count, created_at) ' +
        'SELECT ?, ?, ?, ?, ?, ?, TRY_TO_TIMESTAMP_NTZ(NULLIF(?, \'\'), ' + PIP_TS_FMT + '), ' +
        "TRY_TO_NUMBER(NULLIF(?, ''), 10, 2), TRY_TO_NUMBER(NULLIF(?, '')), 'open', 0, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ",
        [targetId, studentId, String(captureId), raw, norm, category, due || '', money, est]);
    }
    if (!pipIn(touched, targetId)) { touched.push(targetId); }
  }

  var constraints = [];
  var rawCons = (llm.obj.constraints instanceof Array) ? llm.obj.constraints : [];
  for (var c = 0; c < rawCons.length && c < 20; c++) {
    var cc = pipCleanConstraint(rawCons[c]);
    if (!cc) { continue; }
    var cid = pipUuid();
    var created = pipNowLocal();
    pipExec('INSERT INTO PIP.APP.CONSTRAINTS (constraint_id, capture_id, kind, value, created_at) ' +
      'SELECT ?, ?, ?, PARSE_JSON(?), TO_TIMESTAMP_NTZ(?, ' + PIP_TS_FMT + ')',
      [cid, String(captureId), cc.kind, JSON.stringify(cc.value), created]);
    if (cc.kind === 'cash') {
      pipExec('MERGE INTO PIP.APP.PROFILE p ' +
        'USING (SELECT ? AS sid, TRY_TO_NUMBER(?, 10, 2) AS cash, TRY_TO_DATE(NULLIF(?, \'\'), \'YYYY-MM-DD\') AS until_d) s ' +
        'ON p.student_id = s.sid ' +
        'WHEN MATCHED THEN UPDATE SET cash_available = s.cash, budget_until = COALESCE(s.until_d, p.budget_until), ' +
        'updated_at = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ ' +
        'WHEN NOT MATCHED THEN INSERT (student_id, chronotype, cooks_own_meals, cash_available, budget_until, procrastinates_on, updated_at) ' +
        "VALUES (s.sid, 'neutral', TRUE, s.cash, s.until_d, NULL, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ)",
        [studentId, String(cc.value.amount), cc.value.until || '']);
    }
    constraints.push({ constraint_id: cid, capture_id: String(captureId), kind: cc.kind, value: cc.value, created_at: created });
  }

  var tasks = [];
  for (var j = 0; j < touched.length; j++) {
    var row = pipLoadTask(touched[j]);
    if (row) { tasks.push(row); }
  }
  return { tasks: tasks, constraints: constraints, model: llm.model, attempts: llm.attempts };
}

try {
  return pipExtractMain(CAPTURE_ID);
} catch (err) {
  return { tasks: [], constraints: [], model: null, attempts: 0, error: String((err && err.message) || err) };
}
$$;

-- -----------------------------------------------------------------------------
-- (e) BUILD_PLAN
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PIP.APP.BUILD_PLAN(STUDENT_ID VARCHAR, CAPTURE_ID VARCHAR, EXTRA_CONTEXT VARIANT)
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
// ===== common.js =====
// ---------------------------------------------------------------------------
// Shared helpers, inlined by build.mjs at the top of every JavaScript procedure.
// ES5 only (var/function), no template literals, never two dollar signs in a row.
// Times are handled as "naive" wall-clock values: a 'YYYY-MM-DDTHH:MI:SS' string
// is mapped to Date.UTC(...) milliseconds and formatted back with getUTC*, so the
// JavaScript engine's own time zone never matters.
// ---------------------------------------------------------------------------
var PIP_TS_FMT = "'YYYY-MM-DD\"T\"HH24:MI:SS'";
var PIP_CATEGORIES = ['class', 'assignment', 'errand', 'meal', 'money', 'work', 'club', 'social', 'rest'];
var PIP_CONSTRAINT_KINDS = ['time_window', 'cash', 'fixed_block', 'travel'];
var PIP_RULE_IDS = ['irreversible_loss', 'fixed_block_collision', 'basic_needs', 'fits_window', 'academic_deadline'];
var PIP_MODELS = ['claude-sonnet-4-5', 'mistral-large2', 'llama3.1-8b'];
var PIP_COMPLETE_FNS = ['AI_COMPLETE', 'SNOWFLAKE.CORTEX.COMPLETE'];
var PIP_DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
var PIP_DAY_LONG = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
var PIP_MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
var PIP_LAST_OK = null;

function pipIn(arr, v) {
  for (var i = 0; i < arr.length; i++) { if (arr[i] === v) { return true; } }
  return false;
}
function pipIsNil(v) { return v === null || v === undefined; }
function pipStr(v) { return pipIsNil(v) ? '' : String(v); }
function pipNum(v) {
  if (pipIsNil(v) || v === '' || typeof v === 'boolean') { return null; }
  var n = Number(v);
  return isFinite(n) ? n : null;
}
function pipP2(n) { return (n < 10 ? '0' : '') + n; }
function pipTrim(s) { return pipStr(s).replace(/^\s+|\s+$/g, ''); }

// ----- SQL ------------------------------------------------------------------
function pipExec(sql, binds) {
  return snowflake.execute({ sqlText: sql, binds: binds || [] });
}
// cols: upper-case column names/aliases to read from each row
function pipRows(sql, binds, cols) {
  var rs = pipExec(sql, binds);
  var out = [];
  while (rs.next()) {
    var row = {};
    for (var i = 0; i < cols.length; i++) {
      var v = rs.getColumnValue(cols[i]);
      row[cols[i]] = (v === undefined) ? null : v;
    }
    out.push(row);
  }
  return out;
}
function pipScalar(sql, binds) {
  var rs = pipExec(sql, binds);
  if (rs.next()) {
    var v = rs.getColumnValue(1);
    return (v === undefined) ? null : v;
  }
  return null;
}
function pipUuid() { return String(pipScalar('SELECT UUID_STRING()', [])); }
function pipNowLocal() {
  return String(pipScalar('SELECT TO_VARCHAR(CURRENT_TIMESTAMP()::TIMESTAMP_NTZ, ' + PIP_TS_FMT + ')', []));
}

// ----- time -----------------------------------------------------------------
// 'YYYY-MM-DDTHH:MI[:SS]' (or with a space) -> naive ms, else null
function pipParseTs(s) {
  var m = /^(\d{4})-(\d{2})-(\d{2})[T ](\d{1,2}):(\d{2})(?::(\d{2}))?/.exec(pipTrim(s));
  if (!m) { return null; }
  var h = Number(m[4]); var mi = Number(m[5]); var se = Number(m[6] || 0);
  if (h > 23 || mi > 59 || se > 59) { return null; }
  return Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]), h, mi, se);
}
function pipParseDate(s) {
  var m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(pipTrim(s));
  if (!m) { return null; }
  return Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
}
// 'H:MM' / 'HH:MM[:SS]' -> minutes of day, else null
function pipParseHm(s) {
  var m = /^(\d{1,2}):(\d{2})(?::\d{2})?$/.exec(pipTrim(s));
  if (!m) { return null; }
  var h = Number(m[1]); var mi = Number(m[2]);
  if (h > 23 || mi > 59) { return null; }
  return h * 60 + mi;
}
function pipFmtTs(ms) {
  var d = new Date(ms);
  return d.getUTCFullYear() + '-' + pipP2(d.getUTCMonth() + 1) + '-' + pipP2(d.getUTCDate()) + 'T' +
    pipP2(d.getUTCHours()) + ':' + pipP2(d.getUTCMinutes()) + ':' + pipP2(d.getUTCSeconds());
}
function pipFmtDate(ms) { return pipFmtTs(ms).substring(0, 10); }
function pipFmtHmOfDay(min) { return pipP2(Math.floor(min / 60)) + ':' + pipP2(min % 60); }
function pipDayStart(ms) { var d = new Date(ms); return Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()); }
function pipIsoDow(ms) { var d = new Date(ms).getUTCDay(); return d === 0 ? 7 : d; }
// '2:00 PM'
function pipClock(ms) {
  var d = new Date(ms); var h = d.getUTCHours(); var h12 = h % 12 === 0 ? 12 : h % 12;
  return h12 + ':' + pipP2(d.getUTCMinutes()) + (h < 12 ? ' AM' : ' PM');
}
// 'Fri Sep 18'
function pipDayLabel(ms) {
  var d = new Date(ms);
  return PIP_DAY_NAMES[d.getUTCDay()] + ' ' + PIP_MONTHS[d.getUTCMonth()] + ' ' + d.getUTCDate();
}
function pipDaysBetween(fromMs, toMs) { return Math.round((pipDayStart(toMs) - pipDayStart(fromMs)) / 86400000); }
// 'at 5:00 PM today' | 'tomorrow at 11:59 PM' | 'Fri Sep 18 at 5:00 PM'
function pipDueDesc(dueMs, nowMs) {
  var days = pipDaysBetween(nowMs, dueMs);
  if (days === 0) { return 'at ' + pipClock(dueMs) + ' today'; }
  if (days === 1) { return 'tomorrow at ' + pipClock(dueMs); }
  return pipDayLabel(dueMs) + ' at ' + pipClock(dueMs);
}
// '$79' | '$7.50'
function pipMoney(x) {
  var n = Number(x);
  if (Math.abs(n - Math.round(n)) < 0.005) { return '$' + Math.round(n); }
  return '$' + n.toFixed(2);
}
function pipPlural(n, word) { return n + ' ' + word + (n === 1 ? '' : 's'); }

// ----- LLM output -------------------------------------------------------------
// Drops code fences / prose by slicing first '{' .. last '}' (same idea as PIP_EXTRACT_JSON).
function pipExtractJson(text) {
  if (pipIsNil(text)) { return null; }
  var s = String(text);
  var a = s.indexOf('{'); var b = s.lastIndexOf('}');
  if (a < 0 || b <= a) { return null; }
  try {
    var o = JSON.parse(s.substring(a, b + 1));
    return (o && typeof o === 'object' && !(o instanceof Array)) ? o : null;
  } catch (e) {
    return null;
  }
}
// first sentence only; '' when not a usable string
function pipOneSentence(s) {
  if (typeof s !== 'string') { return ''; }
  var t = pipTrim(s.replace(/\s+/g, ' '));
  var m = /^(.+?[.!?])\s+[A-Z]/.exec(t);
  if (m) { t = m[1]; }
  if (t.length > 320) { t = t.substring(0, 317) + '...'; }
  return t;
}

// ----- Cortex -------------------------------------------------------------------
function pipCortexConfig() {
  var cfg = {};
  try {
    var rows = pipRows('SELECT key AS CFG_KEY, value AS CFG_VALUE FROM PIP.APP.CORTEX_CONFIG', [], ['CFG_KEY', 'CFG_VALUE']);
    for (var i = 0; i < rows.length; i++) { cfg[String(rows[i].CFG_KEY)] = rows[i].CFG_VALUE; }
  } catch (e) {
    cfg = {};
  }
  return cfg;
}
// One completion. Walks the fallback chain; returns {text, fn, model, errors}.
function pipComplete(prompt) {
  var cfg = pipCortexConfig();
  var order = [];
  var errors = [];
  function add(fn, model) {
    if (!pipIn(PIP_COMPLETE_FNS, fn)) { return; }
    if (typeof model !== 'string' || !/^[a-z0-9][a-z0-9.\-]*$/.test(model)) { return; }
    for (var k = 0; k < order.length; k++) {
      if (order[k].fn === fn && order[k].model === model) { return; }
    }
    order.push({ fn: fn, model: model });
  }
  if (PIP_LAST_OK) { add(PIP_LAST_OK.fn, PIP_LAST_OK.model); }
  add(cfg.complete_fn || 'AI_COMPLETE', cfg.complete_model || 'claude-sonnet-4-5');
  for (var f = 0; f < PIP_COMPLETE_FNS.length; f++) {
    for (var m = 0; m < PIP_MODELS.length; m++) { add(PIP_COMPLETE_FNS[f], PIP_MODELS[m]); }
  }
  for (var i = 0; i < order.length; i++) {
    var a = order[i];
    try {
      var rs = pipExec('SELECT ' + a.fn + "('" + a.model + "', ?) AS OUT_TEXT", [prompt]);
      if (rs.next()) {
        var v = rs.getColumnValue('OUT_TEXT');
        if (!pipIsNil(v)) {
          PIP_LAST_OK = a;
          return { text: (typeof v === 'string') ? v : JSON.stringify(v), fn: a.fn, model: a.model, errors: errors };
        }
      }
      errors.push(a.fn + '/' + a.model + ': empty response');
    } catch (e) {
      errors.push(a.fn + '/' + a.model + ': ' + String((e && e.message) || e).substring(0, 200));
    }
  }
  return { text: null, fn: null, model: null, errors: errors };
}
// Completion + JSON parse, retried once. Returns {obj, fn, model, attempts, errors}.
function pipCompleteJson(prompt) {
  var errors = [];
  var p = prompt;
  for (var k = 1; k <= 2; k++) {
    var r = pipComplete(p);
    errors = errors.concat(r.errors);
    if (r.text !== null) {
      var obj = pipExtractJson(r.text);
      if (obj) { return { obj: obj, fn: r.fn, model: r.model, attempts: k, errors: errors }; }
      errors.push('attempt ' + k + ': ' + r.model + ' did not return parseable JSON');
    }
    p = prompt + '\n\nIMPORTANT: your previous reply was not valid JSON. Reply with ONLY the JSON object, starting with { and ending with }.';
  }
  return { obj: null, fn: null, model: null, attempts: 2, errors: errors };
}

// ----- rows -----------------------------------------------------------------------
var PIP_TASK_COLS = ['TASK_ID', 'STUDENT_ID', 'CAPTURE_ID', 'RAW_TEXT', 'NORMALIZED_TEXT', 'CATEGORY', 'DUE_S',
  'MONEY', 'EST', 'STATUS', 'DEFERS', 'CREATED_S'];
var PIP_TASK_SELECT = 'SELECT task_id AS TASK_ID, student_id AS STUDENT_ID, capture_id AS CAPTURE_ID, ' +
  'raw_text AS RAW_TEXT, normalized_text AS NORMALIZED_TEXT, category AS CATEGORY, ' +
  'TO_VARCHAR(due_at, ' + PIP_TS_FMT + ') AS DUE_S, money_at_risk::FLOAT AS MONEY, est_minutes::FLOAT AS EST, ' +
  'status AS STATUS, defer_count::FLOAT AS DEFERS, TO_VARCHAR(created_at, ' + PIP_TS_FMT + ') AS CREATED_S ' +
  'FROM PIP.APP.TASKS ';
// Task (types.ts) from a PIP_TASK_SELECT row
function pipTaskJson(r) {
  return {
    task_id: String(r.TASK_ID),
    student_id: String(r.STUDENT_ID),
    capture_id: pipIsNil(r.CAPTURE_ID) ? null : String(r.CAPTURE_ID),
    raw_text: pipStr(r.RAW_TEXT),
    normalized_text: pipStr(r.NORMALIZED_TEXT),
    category: pipStr(r.CATEGORY),
    due_at: pipIsNil(r.DUE_S) ? null : String(r.DUE_S),
    money_at_risk: pipNum(r.MONEY),
    est_minutes: pipNum(r.EST),
    status: pipStr(r.STATUS),
    defer_count: pipNum(r.DEFERS) || 0,
    created_at: pipStr(r.CREATED_S)
  };
}
function pipLoadTask(taskId) {
  var rows = pipRows(PIP_TASK_SELECT + 'WHERE task_id = ?', [taskId], PIP_TASK_COLS);
  return rows.length ? pipTaskJson(rows[0]) : null;
}

// ===== plan_core.js =====
// ---------------------------------------------------------------------------
// BUILD_PLAN part 1: free window, plan items and the deterministic skeleton plan
// (CONTRACT section 4). Pure functions over the state object S built in plan_proc.js.
//
// S = { student_id, capture_id, now_ms, now_str, day_ms, now_min, dow,
//       blocks: [{title, start, end, location}]  (minutes of day, sorted by start),
//       fw: free window (pipFreeWindow), eff: effective minutes,
//       rows: pre-rank rows sorted by score desc, rowsById,
//       chronotype, bed_min, money: {cash, until_ms, budget_until, days, daily, cap},
//       extra: {available_minutes, cash_available, question, previous_plan_id, trigger} }
// row = { task_id, raw_text, title, category, due_ms, due_at, money, est, defer_count,
//         hours_open, first_step, r1..r5, guard, fits, at_risk, curve_kind, score, rules_fired }
// ---------------------------------------------------------------------------
var PIP_RULE_WORDS = {
  irreversible_loss: 'an irreversible loss',
  fixed_block_collision: 'a clash with a fixed block',
  basic_needs: 'a basic need',
  fits_window: 'a first step that fits the window',
  academic_deadline: 'a near academic deadline'
};
var PIP_DAY_END_MIN = 23 * 60 + 59;

function pipStableSort(arr, cmp) {
  var tmp = [];
  for (var i = 0; i < arr.length; i++) { tmp.push({ v: arr[i], i: i }); }
  tmp.sort(function (a, b) { var c = cmp(a.v, b.v); return c !== 0 ? c : a.i - b.i; });
  var out = [];
  for (var j = 0; j < tmp.length; j++) { out.push(tmp[j].v); }
  return out;
}

function pipFreeWindow(nowMs, dayMs, blocks) {
  var nowMin = (nowMs - dayMs) / 60000;
  var ws = nowMin;
  for (var i = 0; i < blocks.length; i++) {
    if (blocks[i].start <= ws && blocks[i].end > ws) { ws = blocks[i].end; }
  }
  var next = null;
  for (var j = 0; j < blocks.length; j++) {
    if (blocks[j].start >= ws && blocks[j].start > nowMin) { next = blocks[j]; break; }
  }
  var endMin = next ? next.start : PIP_DAY_END_MIN;
  var minutes = Math.max(0, Math.floor(endMin - ws + 1e-9));
  var wsMs = (ws === nowMin) ? nowMs : dayMs + Math.round(ws * 60000);
  var label = next
    ? minutes + ' min free until ' + next.title + ', ' + pipClock(dayMs + next.start * 60000)
    : Math.floor(minutes / 60) + ' h ' + (minutes % 60) + ' min free today';
  return {
    ws: ws, end_min: endMin, minutes: minutes, next: next, label: label,
    json: {
      starts_at: pipFmtTs(wsMs),
      ends_at: pipFmtTs(dayMs + endMin * 60000),
      minutes: minutes,
      next_block_title: next ? next.title : null,
      next_block_starts_at: next ? pipFmtTs(dayMs + next.start * 60000) : null,
      label: label
    }
  };
}

function pipBedMin(chronotype) {
  if (chronotype === 'early_bird') { return 22 * 60 + 30; }
  if (chronotype === 'night_owl') { return 23 * 60 + 30; }
  return 23 * 60;
}
function pipMinTs(S, min) { return pipFmtTs(S.day_ms + min * 60000); }
function pipMinClock(S, min) { return pipClock(S.day_ms + min * 60000); }
function pipBy(desc) { return desc.indexOf('at ') === 0 ? 'by ' + desc.substring(3) : 'by ' + desc; }
function pipIsGrocery(r) { return /grocer/i.test(r.title + ' ' + r.raw_text); }
function pipIsDeepWork(r) { return pipIn(['assignment', 'work', 'class'], r.category); }
function pipRuleWords(r) {
  if (!r.rules_fired.length) { return 'none of the urgency rules'; }
  var w = [];
  for (var i = 0; i < r.rules_fired.length; i++) { w.push(PIP_RULE_WORDS[r.rules_fired[i]]); }
  return w.join(', ');
}

function pipBlockItem(S, b, why) {
  return {
    item_id: 'block:' + S.dow + ':' + pipFmtHmOfDay(b.start), kind: 'fixed_block', task_id: null, title: b.title,
    action: 'Be at ' + (b.location || b.title) + ' by ' + pipMinClock(S, b.start),
    category: null, why: why, starts_at: pipMinTs(S, b.start), ends_at: pipMinTs(S, b.end),
    est_minutes: b.end - b.start, due_at: null, money_at_risk: null, location: b.location || null, flag: null,
    rules_fired: [], evidence: [], curve: [], curve_kind: null
  };
}
function pipTaskItem(r) {
  return {
    item_id: r.task_id, kind: 'task', task_id: r.task_id, title: r.title, action: '', category: r.category, why: '',
    starts_at: null, ends_at: null, est_minutes: r.est, due_at: r.due_at, money_at_risk: r.money, location: null,
    flag: r.at_risk ? 'at_risk' : (r.guard ? 'balance_guard' : null),
    rules_fired: r.rules_fired.slice(0), evidence: [], curve: [], curve_kind: r.curve_kind
  };
}

// ----- sentence templates -----------------------------------------------------------
function pipBeforeNext(S) {
  return S.fw.next ? ' before ' + S.fw.next.title + ' at ' + pipMinClock(S, S.fw.next.start) : ' today';
}
function pipDoNowAction(S, r) {
  if (pipIsGrocery(r)) { return 'Buy groceries with a ' + pipMoney(S.money.cap) + ' cap (~' + r.first_step + ' min)'; }
  if (pipIsDeepWork(r) && r.est !== null && r.est > r.first_step) {
    return 'Open ' + r.title + ' and outline the first part for ' + r.first_step + ' min';
  }
  return 'Start now: ' + r.title + ' (~' + r.first_step + ' min)';
}
function pipDoNowWhy(S, r) {
  var before = pipBeforeNext(S);
  if (!r.fits) {
    return 'Nothing fits in the ' + S.eff + ' min you have' + before + ', so start this anyway even though its ' +
      r.first_step + '-min first step will not finish in this window.';
  }
  var fit = 'the ' + r.first_step + '-min first step fits the ' + S.eff + ' min you have' + before;
  if (r.due_ms !== null && r.money !== null && r.money > 0) {
    return pipMoney(r.money) + ' is lost if this is not done ' + pipBy(pipDueDesc(r.due_ms, S.now_ms)) + ', and ' + fit + '.';
  }
  if (r.due_ms !== null) { return 'It is due ' + pipDueDesc(r.due_ms, S.now_ms) + ', and ' + fit + '.'; }
  if (r.r3) { return 'It covers a basic need, and ' + fit + '.'; }
  return 'Nothing more urgent is open, and ' + fit + '.';
}
function pipAtRiskText(S, r) {
  var nb = S.fw.next;
  var need = r.first_step - Math.max(0, S.eff);
  var when = '';
  if (nb) { when = (r.due_ms > S.day_ms + nb.start * 60000) ? ' during ' + nb.title : ' before ' + nb.title; }
  var loss = (r.money !== null && r.money > 0) ? pipMoney(r.money) + ' at risk' : 'the deadline passes';
  return 'Needs ~' + r.first_step + ' min but you have ' + Math.max(0, S.eff) + (nb ? ' before ' + nb.title : '') +
    ', and it is due ' + pipClock(r.due_ms) + when + ' — ' + loss + ' unless you find ' + need + ' more minutes.';
}
function pipGroceryWhy(S) {
  var m = S.money;
  var rest = pipMoney(Math.max(0, m.cash - m.cap));
  if (m.until_ms !== null) {
    return 'You have ' + pipMoney(m.cash) + ' until ' + pipDayLabel(m.until_ms) + ' (about ' + pipMoney(m.daily) +
      '/day), so cap groceries at ' + pipMoney(m.cap) + ' and keep ' + rest + ' for the rest of the week.';
  }
  return 'You have ' + pipMoney(m.cash) + ', so cap groceries at ' + pipMoney(m.cap) + ' and keep ' + rest + ' for everything else.';
}
function pipCanWaitWhy(S, r) {
  var parts = [];
  if (r.due_ms === null) {
    parts.push('No deadline');
  } else {
    var h = (r.due_ms - S.now_ms) / 3600000;
    parts.push('Due ' + pipDueDesc(r.due_ms, S.now_ms) + (h > 48 ? ', more than 48 h away' : ''));
  }
  parts.push((r.money !== null && r.money > 0) ? pipMoney(r.money) + ' at stake but not today' : 'no money at risk');
  parts.push(r.defer_count > 0 ? 'deferred ' + pipPlural(r.defer_count, 'time') + ' so far' : 'not deferred yet');
  return parts.join(', ') + '.';
}
function pipGuardSentence(S, r) {
  return r.title + ': open ' + Math.round(r.hours_open) + ' h and deferred ' + pipPlural(r.defer_count, 'time') +
    ', so it stays on tonight\'s plan at ' + pipMinClock(S, S.bed_min) + '.';
}

// ----- skeleton ------------------------------------------------------------------------
function pipBuildSkeleton(S) {
  var rows = S.rows;
  var nb = S.fw.next;
  var i;

  // do_now: best fitting non-rest (guard items always go to today); else best non-rest
  var cands = [];
  for (i = 0; i < rows.length; i++) {
    if (rows[i].category !== 'rest' && !rows[i].guard) { cands.push(rows[i]); }
  }
  var dn = null;
  for (i = 0; i < cands.length; i++) { if (cands[i].fits) { dn = cands[i]; break; } }
  if (!dn && cands.length) { dn = cands[0]; }

  var skel = { doNowRow: dn, do_now: null, next: null, today: [], can_wait: [], cont: null,
    warnings: [], balance_guard: [], sectionById: {}, itemsById: {} };

  if (dn) {
    var d = pipTaskItem(dn);
    d.action = pipDoNowAction(S, dn);
    d.why = pipDoNowWhy(S, dn);
    d.starts_at = S.now_str;
    d.ends_at = dn.fits ? pipFmtTs(S.now_ms + dn.first_step * 60000) : null;
    if (dn.at_risk) { skel.warnings.push({ task_id: dn.task_id, text: pipAtRiskText(S, dn) }); }
    skel.do_now = d;
    skel.itemsById[dn.task_id] = d;
    skel.sectionById[dn.task_id] = 'do_now';
  }

  // next
  if (nb) {
    var minsUntil = Math.max(0, Math.floor(nb.start - S.now_min));
    var nwhy;
    if (dn && dn.fits) {
      var spare = Math.max(0, S.eff - dn.first_step);
      nwhy = 'After the ' + dn.first_step + '-min ' + dn.title + ' you will have ' + spare + ' min to spare before ' +
        nb.title + ' starts at ' + pipMinClock(S, nb.start) + '.';
    } else {
      nwhy = nb.title + ' starts at ' + pipMinClock(S, nb.start) + ', ' + minsUntil + ' min from now.';
    }
    skel.next = pipBlockItem(S, nb, nwhy);
  } else {
    for (i = 0; i < cands.length; i++) {
      if (cands[i].fits && cands[i] !== dn) {
        var nx = pipTaskItem(cands[i]);
        nx.action = pipDoNowAction(S, cands[i]);
        nx.why = 'After ' + (dn ? dn.title : 'that') + ', this ' + cands[i].first_step + '-min step still fits the ' +
          S.fw.minutes + ' min left today.';
        skel.next = nx;
        break;
      }
    }
  }

  // buckets
  var atRisk = [], dated = [], undated = [], restGuard = [], wait = [];
  for (i = 0; i < rows.length; i++) {
    var r = rows[i];
    if (r === dn) { continue; }
    if (r.at_risk) { atRisk.push(r); }
    else if (r.guard || r.category === 'rest') { restGuard.push(r); }
    else if (r.r1 || r.r2 || r.r3 || r.r5) { if (r.due_ms !== null) { dated.push(r); } else { undated.push(r); } }
    else { wait.push(r); }
  }
  var datedEntries = [];
  var undatedEntries = [];
  for (i = 0; i < dated.length; i++) { datedEntries.push({ row: dated[i], cont: false }); }
  for (i = 0; i < undated.length; i++) { undatedEntries.push({ row: undated[i], cont: false }); }
  // do_now continuation session (assignment/work with more work than the first step)
  if (dn && dn.fits && pipIn(['assignment', 'work'], dn.category) && dn.est !== null && dn.est > dn.first_step) {
    if (dn.due_ms !== null) { datedEntries.push({ row: dn, cont: true }); } else { undatedEntries.unshift({ row: dn, cont: true }); }
  }
  datedEntries = pipStableSort(datedEntries, function (a, b) {
    if (a.row.due_ms !== b.row.due_ms) { return a.row.due_ms - b.row.due_ms; }
    return b.row.score - a.row.score;
  });
  var slotted = datedEntries.concat(undatedEntries);

  // slotting
  var later = [];
  for (i = 0; i < S.blocks.length; i++) { if (nb && S.blocks[i].start > nb.start) { later.push(S.blocks[i]); } }
  var cursor;
  if (nb) { cursor = nb.end + 15; }
  else { cursor = Math.ceil(S.now_min) + (dn && dn.fits ? dn.first_step : 0) + 15; }
  function place(session) {
    var s = cursor;
    var moved = true;
    var loops = 0;
    while (moved && loops < 20) {
      moved = false; loops++;
      for (var k = 0; k < later.length; k++) {
        if (s < later[k].end && s + session > later[k].start) { s = later[k].end + 15; moved = true; }
      }
    }
    if (s + session > 24 * 60) { return null; }
    cursor = s + session + 15;
    return { start: s, end: s + session };
  }

  for (i = 0; i < atRisk.length; i++) {
    var ar = atRisk[i];
    var ai = pipTaskItem(ar);
    var text = pipAtRiskText(S, ar);
    ai.action = 'Only if you find ' + (ar.first_step - Math.max(0, S.eff)) + ' more min: ' + ar.title + ' (~' + ar.first_step + ' min)';
    ai.why = text;
    skel.warnings.push({ task_id: ar.task_id, text: text });
    skel.today.push(ai);
  }
  for (i = 0; i < slotted.length; i++) {
    var en = slotted[i];
    var sr = en.row;
    var it = pipTaskItem(sr);
    var remaining = en.cont ? (sr.est - sr.first_step) : (sr.est !== null ? sr.est : sr.first_step);
    var session = Math.max(5, Math.min(remaining, 90));
    var slot = place(session);
    if (slot) { it.starts_at = pipMinTs(S, slot.start); it.ends_at = pipMinTs(S, slot.end); }
    var at = slot ? pipMinClock(S, slot.start) : null;
    if (en.cont) {
      it.item_id = sr.task_id + '#cont';
      it.title = sr.title + ' (continued)';
      it.est_minutes = remaining;
      it.flag = null;
      it.action = 'Keep going on ' + sr.title + ' for ' + session + ' min';
      it.why = (sr.due_ms !== null ? 'It is due ' + pipDueDesc(sr.due_ms, S.now_ms) + ', so after' : 'After') +
        ' the ' + sr.first_step + '-min start now, this ' + session + '-min session' + (at ? ' at ' + at : '') +
        ' covers more of the remaining ' + remaining + ' min.';
      skel.cont = it;
      skel.itemsById[it.item_id] = it;
      skel.sectionById[it.item_id] = 'today';
      skel.today.push(it);
      continue;
    }
    if (pipIsGrocery(sr)) {
      it.action = 'Buy groceries with a ' + pipMoney(S.money.cap) + ' cap (~' + session + ' min)';
      it.why = pipGroceryWhy(S);
    } else if (sr.due_ms !== null) {
      it.action = (pipIsDeepWork(sr) ? 'Work on ' : 'Do: ') + sr.title + ' for ' + session + ' min';
      it.why = 'It is due ' + pipDueDesc(sr.due_ms, S.now_ms) +
        (at ? ', so this ' + session + '-min session at ' + at + ' keeps it on track.' : ', so fit a session in whenever you can today.');
    } else {
      it.action = 'Do: ' + sr.title + ' (~' + session + ' min)';
      it.why = 'It covers a basic need today' + (at ? ', so ' + session + ' min are set aside at ' + at + '.' : '.');
    }
    skel.today.push(it);
  }
  for (i = 0; i < later.length; i++) {
    skel.today.push(pipBlockItem(S, later[i], later[i].title + ' is fixed from ' + pipMinClock(S, later[i].start) +
      ' to ' + pipMinClock(S, later[i].end) + ', so nothing else is planned then.'));
  }
  restGuard = pipStableSort(restGuard, function (a, b) { return b.score - a.score; });
  for (i = 0; i < restGuard.length; i++) {
    var g = restGuard[i];
    var gi = pipTaskItem(g);
    var bed = pipMinClock(S, S.bed_min);
    gi.starts_at = pipMinTs(S, S.bed_min);
    gi.ends_at = null;
    gi.action = /sleep/i.test(g.title + ' ' + g.raw_text) ? 'Lights out by ' + bed : 'Start ' + g.title + ' at ' + bed;
    if (g.guard) {
      gi.why = g.title + ' has been open ' + Math.round(g.hours_open) + ' h and put off ' + pipPlural(g.defer_count, 'time') +
        ', so Pip protects it at ' + bed + ' tonight.';
      skel.balance_guard.push(pipGuardSentence(S, g));
    } else {
      gi.why = 'Rest keeps tomorrow workable, so it starts at ' + bed + ' tonight.';
    }
    skel.today.push(gi);
  }
  for (i = 0; i < wait.length; i++) {
    var w = pipTaskItem(wait[i]);
    w.action = 'Later: ' + wait[i].title + (wait[i].est !== null ? ' (~' + wait[i].est + ' min)' : '');
    w.why = pipCanWaitWhy(S, wait[i]);
    skel.can_wait.push(w);
  }
  for (i = 0; i < skel.today.length; i++) {
    if (skel.today[i].kind === 'task' && skel.today[i].item_id === skel.today[i].task_id) {
      skel.itemsById[skel.today[i].task_id] = skel.today[i];
      skel.sectionById[skel.today[i].task_id] = 'today';
    }
  }
  for (i = 0; i < skel.can_wait.length; i++) {
    skel.itemsById[skel.can_wait[i].task_id] = skel.can_wait[i];
    skel.sectionById[skel.can_wait[i].task_id] = 'can_wait';
  }

  var windowText = (S.eff < S.fw.minutes) ? 'you have ' + Math.max(0, S.eff) + ' of the ' + S.fw.label : S.fw.label;
  skel.summary = dn
    ? 'Do ' + dn.title + ' now: ' + windowText + '.' + (skel.warnings.length ? ' ' + skel.warnings[0].text : '')
    : 'Nothing needs doing right now: ' + windowText + '.';
  skel.answer = pipAnswer(S, skel);
  return skel;
}

// ===== plan_llm.js =====
// ---------------------------------------------------------------------------
// BUILD_PLAN part 2: deterministic follow-up answer, Cortex prompt, and the
// validation/merge of the LLM reply onto the skeleton (CONTRACT sections 3, 4, 6).
// ---------------------------------------------------------------------------
function pipAnswer(S, skel) {
  var q = S.extra.question ? String(S.extra.question) : '';
  var lq = q.toLowerCase();
  var dn = skel.doNowRow;
  var m = S.money;
  var i;
  if (q && /afford|money|budget|cash|spend/.test(lq)) {
    var risk = 0;
    for (i = 0; i < S.rows.length; i++) { if (S.rows[i].money !== null && S.rows[i].money > 0) { risk += S.rows[i].money; } }
    return 'You have ' + pipMoney(m.cash) +
      (m.until_ms !== null ? ' until ' + pipDayLabel(m.until_ms) + ' (' + pipPlural(m.days, 'day') + ', about ' + pipMoney(m.daily) + '/day)' : '') +
      ', so keep groceries under ' + pipMoney(m.cap) +
      (risk > 0 ? ' and remember ' + pipMoney(risk) + ' is at risk in open tasks.' : '.');
  }
  var wn = /why not (.+)/.exec(lq);
  if (wn && dn) {
    var words = wn[1].replace(/[^a-z0-9 ]/g, ' ').split(/\s+/);
    var best = null;
    var bestScore = 0;
    for (i = 0; i < S.rows.length; i++) {
      var r = S.rows[i];
      if (r === dn) { continue; }
      var hay = (r.title + ' ' + r.raw_text).toLowerCase();
      var sc = 0;
      for (var w = 0; w < words.length; w++) { if (words[w].length >= 3 && hay.indexOf(words[w]) >= 0) { sc++; } }
      if (sc > bestScore) { best = r; bestScore = sc; }
    }
    if (best) {
      return best.title + (best.due_ms !== null ? ' is due ' + pipDueDesc(best.due_ms, S.now_ms) : ' has no deadline') +
        ' and shows ' + pipRuleWords(best) + ', while ' + dn.title +
        (dn.due_ms !== null ? ' is due ' + pipDueDesc(dn.due_ms, S.now_ms) + ' and' : '') + ' shows ' + pipRuleWords(dn) + '.';
    }
  }
  if (S.extra.available_minutes !== null || S.extra.cash_available !== null) {
    var lead = S.extra.available_minutes !== null ? 'With ' + S.eff + ' min' : 'With ' + pipMoney(m.cash);
    if (S.extra.available_minutes !== null && S.extra.cash_available !== null) { lead += ' and ' + pipMoney(m.cash); }
    var tail = '.';
    if (skel.warnings.length) {
      var wt = skel.warnings[0].text;
      tail = '; ' + wt.charAt(0).toLowerCase() + wt.substring(1);
    }
    return lead + ', do now is ' + (dn ? dn.title : 'nothing') + tail;
  }
  return null;
}

function pipLiteItem(it) {
  if (!it) { return null; }
  return { item_id: it.item_id, kind: it.kind, task_id: it.task_id, title: it.title, action: it.action, why: it.why,
    starts_at: it.starts_at, ends_at: it.ends_at, flag: it.flag };
}
function pipLiteList(list) {
  var out = [];
  for (var i = 0; i < list.length; i++) { out.push(pipLiteItem(list[i])); }
  return out;
}

function pipPlanPrompt(S, skel) {
  var i;
  var nb = S.fw.next;
  var later = [];
  for (i = 0; i < S.blocks.length; i++) {
    if (nb && S.blocks[i].start > nb.start) {
      later.push(S.blocks[i].title + ' ' + pipMinClock(S, S.blocks[i].start) + '-' + pipMinClock(S, S.blocks[i].end));
    }
  }
  var pre = [];
  for (i = 0; i < S.rows.length; i++) {
    var r = S.rows[i];
    pre.push({ task_id: r.task_id, text: r.title, category: r.category, due_at: r.due_at, money_at_risk: r.money,
      est_minutes: r.est, first_step_minutes: r.first_step, rules_fired: r.rules_fired, fits: r.fits,
      score: Math.round(r.score * 100) / 100, flag: r.at_risk ? 'at_risk' : (r.guard ? 'balance_guard' : null) });
  }
  var m = S.money;
  var warnings = [];
  for (i = 0; i < skel.warnings.length; i++) { warnings.push(skel.warnings[i].text); }
  var skeleton = { do_now: pipLiteItem(skel.do_now), next: pipLiteItem(skel.next), today: pipLiteList(skel.today), can_wait: pipLiteList(skel.can_wait) };
  return [
    'You are Pip, a calm day planner for a first-time independent university student.',
    'A deterministic ranker already ordered the tasks. Improve the plan wording and return it.',
    'Reply with ONLY one JSON object (no prose, no code fences) with exactly this shape:',
    '{"summary":"...","answer":"... or null","do_now":{"task_id":"...","title":"...","action":"...","why":"...","starts_at":"YYYY-MM-DDTHH:MI:SS or null","ends_at":"... or null"},' +
      '"next":{"item_id":"...","kind":"task or fixed_block","task_id":"... or null","title":"...","action":"...","why":"...","starts_at":"...","ends_at":"..."},' +
      '"today":[{same fields as next}],"can_wait":[{same fields as next}]}',
    '',
    'Ranking rules (already applied in the pre-rank):',
    '1 irreversible_loss: money at risk due within 24 h, or an assignment/work/money deadline within 12 h.',
    '2 fixed_block_collision: the deadline passes before the next fixed block ends, so this free window is the last chance.',
    '3 basic_needs: meals, rest, sleep, groceries, medicine.',
    '4 fits_window: the first step fits the effective free minutes.',
    '5 academic_deadline: an assignment, class or work deadline within 48 h.',
    'Balance guard: a meal or rest task open for 36 h or deferred twice always stays in today.',
    '',
    'Hard requirements:',
    '- Keep do_now as the skeleton do_now task unless it no longer fits the effective minutes.',
    '- Use only the task_ids listed below and never invent tasks. Every task appears exactly once across do_now, today and can_wait; a "<task_id>#cont" continuation item in today is allowed. Keep at_risk and balance_guard items in today.',
    '- next stays the fixed block item when the skeleton has one.',
    '- action is the smallest concrete step. Each why is exactly ONE sentence that cites real times (h:mm AM/PM), dollars and minutes. Never mention scores or rule ids.',
    '- summary is one or two sentences Pip can say out loud. answer: if the student asked a question, answer it in one or two sentences; otherwise null.',
    '- Times are local "YYYY-MM-DDTHH:MI:SS". Keep the skeleton times unless a better slot is obvious, and never overlap a fixed block.',
    '',
    'Situation:',
    '- now: ' + S.now_str + ' (' + PIP_DAY_LONG[new Date(S.now_ms).getUTCDay()] + ')',
    '- free window: ' + S.fw.label + '; effective minutes: ' + S.eff,
    '- next fixed block: ' + (nb ? nb.title + ' ' + pipMinClock(S, nb.start) + '-' + pipMinClock(S, nb.end) + (nb.location ? ' at ' + nb.location : '') : 'none'),
    '- later fixed blocks today: ' + (later.length ? later.join('; ') : 'none'),
    '- cash: ' + pipMoney(m.cash) + (m.until_ms !== null ? ' until ' + pipDayLabel(m.until_ms) + ' (' + pipPlural(m.days, 'day') + ', ' + pipMoney(m.daily) + '/day)' : '') + '; grocery cap ' + pipMoney(m.cap),
    '- chronotype: ' + S.chronotype + ' (bedtime ' + pipMinClock(S, S.bed_min) + ')',
    '- balance guard: ' + (skel.balance_guard.length ? skel.balance_guard.join(' ') : 'none'),
    '- warnings: ' + (warnings.length ? warnings.join(' ') : 'none'),
    '- student question: ' + (S.extra.question ? S.extra.question : 'none'),
    '- minutes the student says they have: ' + (S.extra.available_minutes !== null ? S.extra.available_minutes : 'not stated'),
    '',
    'Pre-rank (highest score first):',
    JSON.stringify(pre),
    '',
    'Skeleton plan:',
    JSON.stringify(skeleton)
  ].join('\n');
}

function pipOverlapsBlock(S, sMin, eMin) {
  for (var i = 0; i < S.blocks.length; i++) {
    if (sMin < S.blocks[i].end && eMin > S.blocks[i].start) { return true; }
  }
  return false;
}
// Copy of a skeleton item with the LLM's wording (and optionally slot times) applied.
function pipApplyText(S, item, src, allowTimes) {
  var t = JSON.parse(JSON.stringify(item));
  if (!src || typeof src !== 'object') { return t; }
  var a = pipTrim(src.action);
  if (a && a.length <= 200) { t.action = a; }
  var w = pipOneSentence(src.why);
  if (w) { t.why = w; }
  var ti = pipTrim(src.title);
  if (t.kind === 'task' && ti && ti.length <= 80) { t.title = ti; }
  if (allowTimes && t.kind === 'task' && t.flag === null && t.category !== 'rest') {
    var s = pipParseTs(src.starts_at);
    var e = pipParseTs(src.ends_at);
    if (s !== null && e !== null && e > s && pipDayStart(s) === S.day_ms && pipDayStart(e) === S.day_ms && s >= S.now_ms) {
      var sm = (s - S.day_ms) / 60000;
      var em = (e - S.day_ms) / 60000;
      if (!pipOverlapsBlock(S, sm, em) && em - sm <= 180) { t.starts_at = pipFmtTs(s); t.ends_at = pipFmtTs(e); }
    }
  }
  return t;
}

// Validation (CONTRACT section 6 / BUILD_PLAN step 8). Section membership always
// comes from the skeleton; the LLM contributes wording, order within a section,
// summary/answer and (checked) slot times.
function pipMergeLlm(S, skel, obj) {
  var out = { do_now: skel.do_now, next: skel.next, today: [], can_wait: [], summary: skel.summary, answer: skel.answer };
  var i;
  if (skel.do_now && obj.do_now && typeof obj.do_now === 'object' && pipTrim(obj.do_now.task_id) === skel.do_now.task_id) {
    out.do_now = pipApplyText(S, skel.do_now, obj.do_now, false);
  }
  if (skel.next && obj.next && typeof obj.next === 'object') {
    var nid = pipTrim(obj.next.item_id);
    var ntid = pipTrim(obj.next.task_id);
    var same = (skel.next.kind === 'fixed_block')
      ? (nid === skel.next.item_id || pipTrim(obj.next.kind) === 'fixed_block')
      : (ntid === skel.next.task_id || nid === skel.next.item_id);
    if (same) { out.next = pipApplyText(S, skel.next, obj.next, false); }
  }
  // LLM entries keyed by skeleton item id (first occurrence wins; unknown ids are dropped).
  // Section membership and order always come from the skeleton, so every pre-ranked task
  // appears exactly once across do_now/today/can_wait and nothing is invented.
  var srcByKey = {};
  var lists = [obj.today, obj.can_wait];
  for (var l = 0; l < lists.length; l++) {
    if (!(lists[l] instanceof Array)) { continue; }
    for (var k = 0; k < lists[l].length; k++) {
      var src = lists[l][k];
      if (!src || typeof src !== 'object') { continue; }
      var id = pipTrim(src.item_id);
      var tid = pipTrim(src.task_id);
      var key = null;
      if (id && skel.itemsById.hasOwnProperty(id)) {
        key = id;
      } else if (tid && id.indexOf('#cont') < 0 && id.indexOf('block:') !== 0 && skel.itemsById.hasOwnProperty(tid)) {
        key = tid;
      }
      if (key !== null && !srcByKey.hasOwnProperty(key)) { srcByKey[key] = src; }
    }
  }
  for (i = 0; i < skel.today.length; i++) {
    var todayItem = skel.today[i];
    out.today.push((todayItem.kind === 'task' && srcByKey.hasOwnProperty(todayItem.item_id))
      ? pipApplyText(S, todayItem, srcByKey[todayItem.item_id], true) : todayItem);
  }
  for (i = 0; i < skel.can_wait.length; i++) {
    var waitItem = skel.can_wait[i];
    out.can_wait.push(srcByKey.hasOwnProperty(waitItem.item_id)
      ? pipApplyText(S, waitItem, srcByKey[waitItem.item_id], false) : waitItem);
  }
  var sm = (typeof obj.summary === 'string') ? pipTrim(obj.summary) : '';
  if (sm && sm.length <= 400) { out.summary = sm; }
  if (S.extra.question) {
    var an = (typeof obj.answer === 'string') ? pipTrim(obj.answer) : '';
    if (an && an.length <= 400) { out.answer = an; }
  }
  return out;
}

// ===== plan_proc.js =====
// ---------------------------------------------------------------------------
// BUILD_PLAN part 3: load data, run the SQL pre-rank, call Cortex, validate,
// insert into PLANS and return the Plan (api/src/types.ts).
// EXTRA_CONTEXT = {now_local, available_minutes?, cash_available?, question?,
//                  previous_plan_id?, trigger, skip_llm?}   (skip_llm is a Pip extension)
// ---------------------------------------------------------------------------
function pipBool(v) { return v === true || v === 1 || String(v).toLowerCase() === 'true'; }

var PIP_PRERANK_SQL = [
  'WITH params AS (',
  '  SELECT TO_TIMESTAMP_NTZ(?, ' + PIP_TS_FMT + ') AS now_ts,',
  '         CAST(? AS NUMBER) AS eff_min,',
  "         TRY_TO_TIMESTAMP_NTZ(NULLIF(?, ''), " + PIP_TS_FMT + ') AS nb_start,',
  "         TRY_TO_TIMESTAMP_NTZ(NULLIF(?, ''), " + PIP_TS_FMT + ') AS nb_end',
  '), base AS (',
  '  SELECT t.task_id, t.raw_text, t.normalized_text, t.category, t.due_at, t.money_at_risk, t.est_minutes,',
  '         COALESCE(t.defer_count, 0) AS defers, t.created_at,',
  '         p.now_ts, p.eff_min, p.nb_start, p.nb_end,',
  "         COALESCE(d.curve, 'linear') AS cfg_curve,",
  '         COALESCE(d.half_life_hours, 72) AS cfg_half_life,',
  '         COALESCE(d.floor_weight, 0.1) AS cfg_floor,',
  '         DATEDIFF(second, p.now_ts, t.due_at) / 3600.0 AS hours_to_due,',
  '         DATEDIFF(second, t.created_at, p.now_ts) / 3600.0 AS hours_open,',
  '         PIP.APP.PIP_FIRST_STEP_MINUTES(t.category, t.est_minutes) AS first_step',
  '  FROM PIP.APP.TASKS t',
  '  CROSS JOIN params p',
  '  LEFT JOIN PIP.APP.DECAY_CONFIG d ON d.category = t.category',
  "  WHERE t.student_id = ? AND t.status IN ('open', 'deferred') AND (t.due_at IS NULL OR t.due_at > p.now_ts)",
  '), ruled AS (',
  '  SELECT b.*,',
  '    ((COALESCE(b.money_at_risk, 0) > 0 AND b.due_at IS NOT NULL AND b.due_at <= DATEADD(hour, 24, b.now_ts))',
  "      OR (b.category IN ('assignment', 'work', 'money') AND b.due_at IS NOT NULL AND b.due_at <= DATEADD(hour, 12, b.now_ts))) AS r1,",
  '    (b.due_at IS NOT NULL AND b.nb_start IS NOT NULL AND b.nb_start > b.now_ts AND b.due_at <= b.nb_end) AS r2,',
  "    (b.category IN ('meal', 'rest') OR REGEXP_INSTR(LOWER(COALESCE(b.normalized_text, '') || ' ' || COALESCE(b.raw_text, '')),",
  "      'grocer|medic|pharm|prescription|sleep|lunch|dinner|breakfast|meal') > 0) AS r3,",
  '    (b.eff_min > 0 AND b.first_step <= b.eff_min) AS r4,',
  "    (b.category IN ('assignment', 'class', 'work') AND b.due_at IS NOT NULL AND b.due_at <= DATEADD(hour, 48, b.now_ts)) AS r5,",
  "    (b.category IN ('meal', 'rest') AND (COALESCE(b.hours_open, 0) >= 36 OR b.defers >= 2)) AS guard_fired,",
  "    IFF(COALESCE(b.money_at_risk, 0) > 0 AND b.due_at IS NOT NULL, 'cliff', b.cfg_curve) AS curve_kind",
  '  FROM base b',
  ')',
  'SELECT r.task_id AS TASK_ID, r.raw_text AS RAW_TEXT, r.normalized_text AS NORMALIZED_TEXT, r.category AS CATEGORY,',
  '       TO_VARCHAR(r.due_at, ' + PIP_TS_FMT + ') AS DUE_S, r.money_at_risk::FLOAT AS MONEY, r.est_minutes::FLOAT AS EST,',
  '       r.defers::FLOAT AS DEFERS, r.hours_open::FLOAT AS HOURS_OPEN, r.first_step::FLOAT AS FIRST_STEP,',
  '       r.r1 AS R1, r.r2 AS R2, r.r3 AS R3, r.r4 AS R4, r.r5 AS R5, r.guard_fired AS GUARD_FIRED, r.curve_kind AS CURVE_KIND,',
  '       (10000 * IFF(r.r1, 1, 0) + 1000 * IFF(r.r2, 1, 0) + 100 * IFF(r.r3, 1, 0) + 10 * IFF(r.r4, 1, 0) + IFF(r.r5, 1, 0)',
  '        + ROUND(0.99 * PIP.APP.PIP_DECAY_COST(r.curve_kind, r.cfg_floor, r.cfg_half_life, r.hours_to_due, r.hours_open, r.defers, 2), 4))::FLOAT AS SCORE',
  'FROM ruled r',
  'ORDER BY SCORE DESC, TASK_ID'
].join('\n');
var PIP_PRERANK_COLS = ['TASK_ID', 'RAW_TEXT', 'NORMALIZED_TEXT', 'CATEGORY', 'DUE_S', 'MONEY', 'EST', 'DEFERS', 'HOURS_OPEN',
  'FIRST_STEP', 'R1', 'R2', 'R3', 'R4', 'R5', 'GUARD_FIRED', 'CURVE_KIND', 'SCORE'];

function pipBuildPlanMain(studentIdArg, captureIdArg, extraArg) {
  var i;
  var sid = pipTrim(studentIdArg);
  var cid = pipTrim(captureIdArg);
  var ctx = extraArg;
  if (typeof ctx === 'string') { try { ctx = JSON.parse(ctx); } catch (e) { ctx = {}; } }
  if (!ctx || typeof ctx !== 'object' || ctx instanceof Array) { ctx = {}; }
  if (!sid) { return { error: 'student_id is required' }; }

  // 1. scenario clock
  var nowMs = pipParseTs(ctx.now_local);
  if (nowMs === null) { nowMs = pipParseTs(pipNowLocal()); }
  var nowStr = pipFmtTs(nowMs);
  var dayMs = pipDayStart(nowMs);
  var nowMin = (nowMs - dayMs) / 60000;
  var dow = pipIsoDow(nowMs);
  var ctxMinutes = pipNum(ctx.available_minutes);
  var ctxCash = pipNum(ctx.cash_available);
  var extra = {
    available_minutes: (ctxMinutes !== null && ctxMinutes >= 0) ? Math.round(ctxMinutes) : null,
    cash_available: (ctxCash !== null && ctxCash >= 0) ? Math.round(ctxCash * 100) / 100 : null,
    question: (typeof ctx.question === 'string' && pipTrim(ctx.question)) ? pipTrim(ctx.question) : null,
    previous_plan_id: pipTrim(ctx.previous_plan_id) || null,
    trigger: pipIn(['capture', 'rerank', 'seed'], pipTrim(ctx.trigger)) ? pipTrim(ctx.trigger) : 'capture'
  };

  // 2. today's blocks = timetable + fixed_block constraints of this capture (dedup by start time)
  var blocks = [];
  var tt = pipRows("SELECT title AS TITLE, TO_VARCHAR(starts_at, 'HH24:MI') AS START_HM, TO_VARCHAR(ends_at, 'HH24:MI') AS END_HM, " +
    'location AS LOCATION FROM PIP.APP.TIMETABLE WHERE student_id = ? AND day_of_week = ? ORDER BY starts_at',
    [sid, dow], ['TITLE', 'START_HM', 'END_HM', 'LOCATION']);
  for (i = 0; i < tt.length; i++) {
    var bs = pipParseHm(tt[i].START_HM);
    var be = pipParseHm(tt[i].END_HM);
    if (bs === null) { continue; }
    if (be === null || be <= bs) { be = Math.min(bs + 60, 24 * 60); }
    blocks.push({ title: pipStr(tt[i].TITLE), start: bs, end: be, location: pipTrim(tt[i].LOCATION) || null });
  }
  var timeWindow = null;
  var cashC = null;
  if (cid) {
    var cons = pipRows('SELECT kind AS KIND, value AS VAL FROM PIP.APP.CONSTRAINTS WHERE capture_id = ? ORDER BY created_at',
      [cid], ['KIND', 'VAL']);
    for (i = 0; i < cons.length; i++) {
      var v = cons[i].VAL;
      if (typeof v === 'string') { try { v = JSON.parse(v); } catch (e2) { v = null; } }
      if (!v || typeof v !== 'object') { continue; }
      var kind = pipStr(cons[i].KIND);
      if (kind === 'fixed_block') {
        var cs = pipParseHm(v.starts_at);
        if (cs === null) { continue; }
        var dup = false;
        for (var k = 0; k < blocks.length; k++) { if (blocks[k].start === cs) { dup = true; } }
        if (dup) { continue; }
        var ce = pipParseHm(v.ends_at);
        if (ce === null || ce <= cs) { ce = Math.min(cs + 60, 24 * 60); }
        blocks.push({ title: pipTrim(v.title) || 'Class', start: cs, end: ce, location: pipTrim(v.location) || null });
      } else if (kind === 'time_window') {
        var twm = pipNum(v.minutes);
        if (twm !== null && twm > 0) { timeWindow = Math.round(twm); }
      } else if (kind === 'cash') {
        var amt = pipNum(v.amount);
        if (amt !== null && amt >= 0) { cashC = { amount: amt, until_ms: pipParseDate(v.until) }; }
      }
    }
  }
  blocks = pipStableSort(blocks, function (a, b) { return a.start !== b.start ? a.start - b.start : a.end - b.end; });
  var fw = pipFreeWindow(nowMs, dayMs, blocks);
  if (extra.available_minutes === null && timeWindow !== null) { extra.available_minutes = timeWindow; }
  var eff = extra.available_minutes !== null ? Math.min(fw.minutes, extra.available_minutes) : fw.minutes;

  // 3. money: capture cash constraint overrides PROFILE, EXTRA_CONTEXT cash overrides both
  var prof = pipRows("SELECT chronotype AS CHRONOTYPE, cash_available::FLOAT AS CASH, TO_VARCHAR(budget_until, 'YYYY-MM-DD') AS UNTIL_S " +
    'FROM PIP.APP.PROFILE WHERE student_id = ?', [sid], ['CHRONOTYPE', 'CASH', 'UNTIL_S']);
  var chronotype = (prof.length && pipIn(['early_bird', 'neutral', 'night_owl'], pipStr(prof[0].CHRONOTYPE))) ? pipStr(prof[0].CHRONOTYPE) : 'neutral';
  var cash = prof.length ? (pipNum(prof[0].CASH) || 0) : 0;
  var untilMs = prof.length ? pipParseDate(prof[0].UNTIL_S) : null;
  if (cashC) { cash = cashC.amount; if (cashC.until_ms !== null) { untilMs = cashC.until_ms; } }
  if (extra.cash_available !== null) { cash = extra.cash_available; }
  var days = (untilMs !== null) ? Math.max(1, pipDaysBetween(dayMs, untilMs)) : null;
  var money = {
    cash: cash, until_ms: untilMs, budget_until: untilMs !== null ? pipFmtDate(untilMs) : null, days: days,
    daily: days !== null ? Math.round(cash / days * 100) / 100 : null, cap: Math.floor(cash * 0.6)
  };

  // 4. past-due open tasks expire
  pipExec("UPDATE PIP.APP.TASKS SET status = 'expired' WHERE student_id = ? AND status IN ('open', 'deferred') " +
    'AND due_at IS NOT NULL AND due_at <= TO_TIMESTAMP_NTZ(?, ' + PIP_TS_FMT + ')', [sid, nowStr]);

  // 5. SQL pre-rank (R1..R5, balance guard, first step, fits, score)
  var nb = fw.next;
  var q = pipRows(PIP_PRERANK_SQL, [nowStr, eff, nb ? pipFmtTs(dayMs + nb.start * 60000) : '',
    nb ? pipFmtTs(dayMs + nb.end * 60000) : '', sid], PIP_PRERANK_COLS);
  var rows = [];
  var rowsById = {};
  for (i = 0; i < q.length; i++) {
    var cat = pipStr(q[i].CATEGORY);
    var r = {
      task_id: String(q[i].TASK_ID), raw_text: pipStr(q[i].RAW_TEXT),
      title: pipStr(q[i].NORMALIZED_TEXT) || pipStr(q[i].RAW_TEXT),
      category: pipIn(PIP_CATEGORIES, cat) ? cat : 'errand',
      due_at: pipIsNil(q[i].DUE_S) ? null : String(q[i].DUE_S), due_ms: pipParseTs(q[i].DUE_S),
      money: pipNum(q[i].MONEY), est: pipNum(q[i].EST), defer_count: pipNum(q[i].DEFERS) || 0,
      hours_open: pipNum(q[i].HOURS_OPEN) || 0, first_step: pipNum(q[i].FIRST_STEP) || 15,
      r1: pipBool(q[i].R1), r2: pipBool(q[i].R2), r3: pipBool(q[i].R3), r4: pipBool(q[i].R4), r5: pipBool(q[i].R5),
      guard: pipBool(q[i].GUARD_FIRED), curve_kind: pipStr(q[i].CURVE_KIND) || 'linear', score: pipNum(q[i].SCORE) || 0
    };
    r.fits = r.r4;
    r.at_risk = r.r1 && r.r2 && !r.r4;
    r.rules_fired = [];
    if (r.r1) { r.rules_fired.push('irreversible_loss'); }
    if (r.r2) { r.rules_fired.push('fixed_block_collision'); }
    if (r.r3) { r.rules_fired.push('basic_needs'); }
    if (r.r4) { r.rules_fired.push('fits_window'); }
    if (r.r5) { r.rules_fired.push('academic_deadline'); }
    rows.push(r);
    rowsById[r.task_id] = r;
  }

  var S = {
    student_id: sid, capture_id: cid || null, now_ms: nowMs, now_str: nowStr, day_ms: dayMs, now_min: nowMin, dow: dow,
    blocks: blocks, fw: fw, eff: eff, rows: rows, rowsById: rowsById, chronotype: chronotype,
    bed_min: pipBedMin(chronotype), money: money, extra: extra
  };

  // 6. deterministic skeleton (also the no-LLM plan)
  var skel = pipBuildSkeleton(S);
  var fin = { do_now: skel.do_now, next: skel.next, today: skel.today, can_wait: skel.can_wait, summary: skel.summary, answer: skel.answer };
  var model = 'sql-prerank';
  var cortexErrors = [];

  // 7-8. Cortex wording + validation
  if (rows.length > 0 && !pipBool(ctx.skip_llm)) {
    var llm = pipCompleteJson(pipPlanPrompt(S, skel));
    if (llm.obj) {
      fin = pipMergeLlm(S, skel, llm.obj);
      model = llm.model;
    } else {
      cortexErrors = llm.errors;
    }
  }

  // 10. reasoning
  var preRank = [];
  for (i = 0; i < rows.length; i++) {
    preRank.push({ task_id: rows[i].task_id, score: Math.round(rows[i].score * 10000) / 10000, rules_fired: rows[i].rules_fired,
      first_step_minutes: rows[i].first_step, fits: rows[i].fits });
  }
  var reasoning = {
    summary: fin.summary,
    now: nowStr,
    free_window: fw.json,
    effective_minutes: eff,
    context: { available_minutes: extra.available_minutes, cash_available: extra.cash_available, question: extra.question },
    cash_available: cash,
    budget_until: money.budget_until,
    days_until_budget: days,
    daily_budget: money.daily,
    warnings: skel.warnings,
    balance_guard: skel.balance_guard,
    answer: fin.answer,
    pre_rank: preRank,
    trigger: extra.trigger,
    previous_plan_id: extra.previous_plan_id
  };

  // 11. append to PLANS and return the Plan
  var planId = pipUuid();
  var createdAt = pipNowLocal();
  pipExec('INSERT INTO PIP.APP.PLANS (plan_id, student_id, capture_id, do_now, next, today, can_wait, reasoning, model, created_at) ' +
    "SELECT ?, ?, NULLIF(?, ''), PARSE_JSON(?), PARSE_JSON(?), PARSE_JSON(?), PARSE_JSON(?), PARSE_JSON(?), ?, TO_TIMESTAMP_NTZ(?, " + PIP_TS_FMT + ')',
    [planId, sid, cid, JSON.stringify(fin.do_now), JSON.stringify(fin.next), JSON.stringify(fin.today),
      JSON.stringify(fin.can_wait), JSON.stringify(reasoning), model, createdAt]);
  var plan = {
    plan_id: planId, student_id: sid, capture_id: cid || null, created_at: createdAt, model: model,
    do_now: fin.do_now, next: fin.next, today: fin.today, can_wait: fin.can_wait, reasoning: reasoning
  };
  if (cortexErrors.length) { plan.cortex_errors = cortexErrors; }
  return plan;
}

try {
  return pipBuildPlanMain(STUDENT_ID, CAPTURE_ID, EXTRA_CONTEXT);
} catch (err) {
  return { error: String((err && err.message) || err) };
}
$$;

-- -----------------------------------------------------------------------------
-- (f) RECORD_ACTION
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PIP.APP.RECORD_ACTION(STUDENT_ID VARCHAR, PLAN_ID VARCHAR, TASK_ID VARCHAR, KIND VARCHAR)
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
// ===== common.js =====
// ---------------------------------------------------------------------------
// Shared helpers, inlined by build.mjs at the top of every JavaScript procedure.
// ES5 only (var/function), no template literals, never two dollar signs in a row.
// Times are handled as "naive" wall-clock values: a 'YYYY-MM-DDTHH:MI:SS' string
// is mapped to Date.UTC(...) milliseconds and formatted back with getUTC*, so the
// JavaScript engine's own time zone never matters.
// ---------------------------------------------------------------------------
var PIP_TS_FMT = "'YYYY-MM-DD\"T\"HH24:MI:SS'";
var PIP_CATEGORIES = ['class', 'assignment', 'errand', 'meal', 'money', 'work', 'club', 'social', 'rest'];
var PIP_CONSTRAINT_KINDS = ['time_window', 'cash', 'fixed_block', 'travel'];
var PIP_RULE_IDS = ['irreversible_loss', 'fixed_block_collision', 'basic_needs', 'fits_window', 'academic_deadline'];
var PIP_MODELS = ['claude-sonnet-4-5', 'mistral-large2', 'llama3.1-8b'];
var PIP_COMPLETE_FNS = ['AI_COMPLETE', 'SNOWFLAKE.CORTEX.COMPLETE'];
var PIP_DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
var PIP_DAY_LONG = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
var PIP_MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
var PIP_LAST_OK = null;

function pipIn(arr, v) {
  for (var i = 0; i < arr.length; i++) { if (arr[i] === v) { return true; } }
  return false;
}
function pipIsNil(v) { return v === null || v === undefined; }
function pipStr(v) { return pipIsNil(v) ? '' : String(v); }
function pipNum(v) {
  if (pipIsNil(v) || v === '' || typeof v === 'boolean') { return null; }
  var n = Number(v);
  return isFinite(n) ? n : null;
}
function pipP2(n) { return (n < 10 ? '0' : '') + n; }
function pipTrim(s) { return pipStr(s).replace(/^\s+|\s+$/g, ''); }

// ----- SQL ------------------------------------------------------------------
function pipExec(sql, binds) {
  return snowflake.execute({ sqlText: sql, binds: binds || [] });
}
// cols: upper-case column names/aliases to read from each row
function pipRows(sql, binds, cols) {
  var rs = pipExec(sql, binds);
  var out = [];
  while (rs.next()) {
    var row = {};
    for (var i = 0; i < cols.length; i++) {
      var v = rs.getColumnValue(cols[i]);
      row[cols[i]] = (v === undefined) ? null : v;
    }
    out.push(row);
  }
  return out;
}
function pipScalar(sql, binds) {
  var rs = pipExec(sql, binds);
  if (rs.next()) {
    var v = rs.getColumnValue(1);
    return (v === undefined) ? null : v;
  }
  return null;
}
function pipUuid() { return String(pipScalar('SELECT UUID_STRING()', [])); }
function pipNowLocal() {
  return String(pipScalar('SELECT TO_VARCHAR(CURRENT_TIMESTAMP()::TIMESTAMP_NTZ, ' + PIP_TS_FMT + ')', []));
}

// ----- time -----------------------------------------------------------------
// 'YYYY-MM-DDTHH:MI[:SS]' (or with a space) -> naive ms, else null
function pipParseTs(s) {
  var m = /^(\d{4})-(\d{2})-(\d{2})[T ](\d{1,2}):(\d{2})(?::(\d{2}))?/.exec(pipTrim(s));
  if (!m) { return null; }
  var h = Number(m[4]); var mi = Number(m[5]); var se = Number(m[6] || 0);
  if (h > 23 || mi > 59 || se > 59) { return null; }
  return Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]), h, mi, se);
}
function pipParseDate(s) {
  var m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(pipTrim(s));
  if (!m) { return null; }
  return Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
}
// 'H:MM' / 'HH:MM[:SS]' -> minutes of day, else null
function pipParseHm(s) {
  var m = /^(\d{1,2}):(\d{2})(?::\d{2})?$/.exec(pipTrim(s));
  if (!m) { return null; }
  var h = Number(m[1]); var mi = Number(m[2]);
  if (h > 23 || mi > 59) { return null; }
  return h * 60 + mi;
}
function pipFmtTs(ms) {
  var d = new Date(ms);
  return d.getUTCFullYear() + '-' + pipP2(d.getUTCMonth() + 1) + '-' + pipP2(d.getUTCDate()) + 'T' +
    pipP2(d.getUTCHours()) + ':' + pipP2(d.getUTCMinutes()) + ':' + pipP2(d.getUTCSeconds());
}
function pipFmtDate(ms) { return pipFmtTs(ms).substring(0, 10); }
function pipFmtHmOfDay(min) { return pipP2(Math.floor(min / 60)) + ':' + pipP2(min % 60); }
function pipDayStart(ms) { var d = new Date(ms); return Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()); }
function pipIsoDow(ms) { var d = new Date(ms).getUTCDay(); return d === 0 ? 7 : d; }
// '2:00 PM'
function pipClock(ms) {
  var d = new Date(ms); var h = d.getUTCHours(); var h12 = h % 12 === 0 ? 12 : h % 12;
  return h12 + ':' + pipP2(d.getUTCMinutes()) + (h < 12 ? ' AM' : ' PM');
}
// 'Fri Sep 18'
function pipDayLabel(ms) {
  var d = new Date(ms);
  return PIP_DAY_NAMES[d.getUTCDay()] + ' ' + PIP_MONTHS[d.getUTCMonth()] + ' ' + d.getUTCDate();
}
function pipDaysBetween(fromMs, toMs) { return Math.round((pipDayStart(toMs) - pipDayStart(fromMs)) / 86400000); }
// 'at 5:00 PM today' | 'tomorrow at 11:59 PM' | 'Fri Sep 18 at 5:00 PM'
function pipDueDesc(dueMs, nowMs) {
  var days = pipDaysBetween(nowMs, dueMs);
  if (days === 0) { return 'at ' + pipClock(dueMs) + ' today'; }
  if (days === 1) { return 'tomorrow at ' + pipClock(dueMs); }
  return pipDayLabel(dueMs) + ' at ' + pipClock(dueMs);
}
// '$79' | '$7.50'
function pipMoney(x) {
  var n = Number(x);
  if (Math.abs(n - Math.round(n)) < 0.005) { return '$' + Math.round(n); }
  return '$' + n.toFixed(2);
}
function pipPlural(n, word) { return n + ' ' + word + (n === 1 ? '' : 's'); }

// ----- LLM output -------------------------------------------------------------
// Drops code fences / prose by slicing first '{' .. last '}' (same idea as PIP_EXTRACT_JSON).
function pipExtractJson(text) {
  if (pipIsNil(text)) { return null; }
  var s = String(text);
  var a = s.indexOf('{'); var b = s.lastIndexOf('}');
  if (a < 0 || b <= a) { return null; }
  try {
    var o = JSON.parse(s.substring(a, b + 1));
    return (o && typeof o === 'object' && !(o instanceof Array)) ? o : null;
  } catch (e) {
    return null;
  }
}
// first sentence only; '' when not a usable string
function pipOneSentence(s) {
  if (typeof s !== 'string') { return ''; }
  var t = pipTrim(s.replace(/\s+/g, ' '));
  var m = /^(.+?[.!?])\s+[A-Z]/.exec(t);
  if (m) { t = m[1]; }
  if (t.length > 320) { t = t.substring(0, 317) + '...'; }
  return t;
}

// ----- Cortex -------------------------------------------------------------------
function pipCortexConfig() {
  var cfg = {};
  try {
    var rows = pipRows('SELECT key AS CFG_KEY, value AS CFG_VALUE FROM PIP.APP.CORTEX_CONFIG', [], ['CFG_KEY', 'CFG_VALUE']);
    for (var i = 0; i < rows.length; i++) { cfg[String(rows[i].CFG_KEY)] = rows[i].CFG_VALUE; }
  } catch (e) {
    cfg = {};
  }
  return cfg;
}
// One completion. Walks the fallback chain; returns {text, fn, model, errors}.
function pipComplete(prompt) {
  var cfg = pipCortexConfig();
  var order = [];
  var errors = [];
  function add(fn, model) {
    if (!pipIn(PIP_COMPLETE_FNS, fn)) { return; }
    if (typeof model !== 'string' || !/^[a-z0-9][a-z0-9.\-]*$/.test(model)) { return; }
    for (var k = 0; k < order.length; k++) {
      if (order[k].fn === fn && order[k].model === model) { return; }
    }
    order.push({ fn: fn, model: model });
  }
  if (PIP_LAST_OK) { add(PIP_LAST_OK.fn, PIP_LAST_OK.model); }
  add(cfg.complete_fn || 'AI_COMPLETE', cfg.complete_model || 'claude-sonnet-4-5');
  for (var f = 0; f < PIP_COMPLETE_FNS.length; f++) {
    for (var m = 0; m < PIP_MODELS.length; m++) { add(PIP_COMPLETE_FNS[f], PIP_MODELS[m]); }
  }
  for (var i = 0; i < order.length; i++) {
    var a = order[i];
    try {
      var rs = pipExec('SELECT ' + a.fn + "('" + a.model + "', ?) AS OUT_TEXT", [prompt]);
      if (rs.next()) {
        var v = rs.getColumnValue('OUT_TEXT');
        if (!pipIsNil(v)) {
          PIP_LAST_OK = a;
          return { text: (typeof v === 'string') ? v : JSON.stringify(v), fn: a.fn, model: a.model, errors: errors };
        }
      }
      errors.push(a.fn + '/' + a.model + ': empty response');
    } catch (e) {
      errors.push(a.fn + '/' + a.model + ': ' + String((e && e.message) || e).substring(0, 200));
    }
  }
  return { text: null, fn: null, model: null, errors: errors };
}
// Completion + JSON parse, retried once. Returns {obj, fn, model, attempts, errors}.
function pipCompleteJson(prompt) {
  var errors = [];
  var p = prompt;
  for (var k = 1; k <= 2; k++) {
    var r = pipComplete(p);
    errors = errors.concat(r.errors);
    if (r.text !== null) {
      var obj = pipExtractJson(r.text);
      if (obj) { return { obj: obj, fn: r.fn, model: r.model, attempts: k, errors: errors }; }
      errors.push('attempt ' + k + ': ' + r.model + ' did not return parseable JSON');
    }
    p = prompt + '\n\nIMPORTANT: your previous reply was not valid JSON. Reply with ONLY the JSON object, starting with { and ending with }.';
  }
  return { obj: null, fn: null, model: null, attempts: 2, errors: errors };
}

// ----- rows -----------------------------------------------------------------------
var PIP_TASK_COLS = ['TASK_ID', 'STUDENT_ID', 'CAPTURE_ID', 'RAW_TEXT', 'NORMALIZED_TEXT', 'CATEGORY', 'DUE_S',
  'MONEY', 'EST', 'STATUS', 'DEFERS', 'CREATED_S'];
var PIP_TASK_SELECT = 'SELECT task_id AS TASK_ID, student_id AS STUDENT_ID, capture_id AS CAPTURE_ID, ' +
  'raw_text AS RAW_TEXT, normalized_text AS NORMALIZED_TEXT, category AS CATEGORY, ' +
  'TO_VARCHAR(due_at, ' + PIP_TS_FMT + ') AS DUE_S, money_at_risk::FLOAT AS MONEY, est_minutes::FLOAT AS EST, ' +
  'status AS STATUS, defer_count::FLOAT AS DEFERS, TO_VARCHAR(created_at, ' + PIP_TS_FMT + ') AS CREATED_S ' +
  'FROM PIP.APP.TASKS ';
// Task (types.ts) from a PIP_TASK_SELECT row
function pipTaskJson(r) {
  return {
    task_id: String(r.TASK_ID),
    student_id: String(r.STUDENT_ID),
    capture_id: pipIsNil(r.CAPTURE_ID) ? null : String(r.CAPTURE_ID),
    raw_text: pipStr(r.RAW_TEXT),
    normalized_text: pipStr(r.NORMALIZED_TEXT),
    category: pipStr(r.CATEGORY),
    due_at: pipIsNil(r.DUE_S) ? null : String(r.DUE_S),
    money_at_risk: pipNum(r.MONEY),
    est_minutes: pipNum(r.EST),
    status: pipStr(r.STATUS),
    defer_count: pipNum(r.DEFERS) || 0,
    created_at: pipStr(r.CREATED_S)
  };
}
function pipLoadTask(taskId) {
  var rows = pipRows(PIP_TASK_SELECT + 'WHERE task_id = ?', [taskId], PIP_TASK_COLS);
  return rows.length ? pipTaskJson(rows[0]) : null;
}

// ===== record_action.js =====
// ---------------------------------------------------------------------------
// RECORD_ACTION(STUDENT_ID, PLAN_ID, TASK_ID, KIND) RETURNS VARIANT
// Returns an Action (types.ts) and applies the task status change:
//   done -> 'done' | defer -> 'deferred' and defer_count + 1 | drop -> 'dropped' | start_now -> no change
// Invalid input returns {error}.
// ---------------------------------------------------------------------------
function pipRecordActionMain(studentId, planId, taskId, kind) {
  var k = pipTrim(kind);
  if (!pipIn(['start_now', 'done', 'defer', 'drop'], k)) {
    return { error: 'invalid kind: ' + pipStr(kind) };
  }
  var sid = pipTrim(studentId);
  var pid = pipTrim(planId);
  if (!sid || !pid) {
    return { error: 'student_id and plan_id are required' };
  }
  var tid = pipTrim(taskId);
  var actionId = pipUuid();
  var created = pipNowLocal();
  pipExec('INSERT INTO PIP.APP.ACTIONS (action_id, student_id, plan_id, task_id, kind, created_at) ' +
    "SELECT ?, ?, ?, NULLIF(?, ''), ?, TO_TIMESTAMP_NTZ(?, " + PIP_TS_FMT + ')',
    [actionId, sid, pid, tid, k, created]);
  if (tid) {
    if (k === 'done') {
      pipExec("UPDATE PIP.APP.TASKS SET status = 'done' WHERE task_id = ? AND student_id = ?", [tid, sid]);
    } else if (k === 'defer') {
      pipExec("UPDATE PIP.APP.TASKS SET status = 'deferred', defer_count = COALESCE(defer_count, 0) + 1 WHERE task_id = ? AND student_id = ?", [tid, sid]);
    } else if (k === 'drop') {
      pipExec("UPDATE PIP.APP.TASKS SET status = 'dropped' WHERE task_id = ? AND student_id = ?", [tid, sid]);
    }
  }
  return {
    action_id: actionId,
    student_id: sid,
    plan_id: pid,
    task_id: tid ? tid : null,
    kind: k,
    created_at: created
  };
}

try {
  return pipRecordActionMain(STUDENT_ID, PLAN_ID, TASK_ID, KIND);
} catch (err) {
  return { error: String((err && err.message) || err) };
}
$$;

SHOW PROCEDURES IN SCHEMA PIP.APP;
