-- =============================================================================
-- Pip / Snowflake layer  --  03_functions.sql
-- GENERATED by snowflake/build.mjs from snowflake/src/*. Edit the sources and
-- run `node snowflake/build.mjs`; do not hand-edit this file.
--
-- Contents
--   (a) Cortex verification block  -> CORTEX_CONFIG
--   (b) SQL helper UDFs: PIP_EXTRACT_JSON, PIP_FIRST_STEP_MINUTES, PIP_DECAY_COST, PIP_FMT_TIME
--   (c) Cortex call chain (a JavaScript helper inlined in each procedure; it reads
--       CORTEX_CONFIG, then walks AI_COMPLETE -> SNOWFLAKE.CORTEX.COMPLETE over
--       claude-sonnet-4-5 -> mistral-large2 -> llama3.1-8b with try/catch per attempt)
--   (d) EXTRACT_FROM_TRANSCRIPT(CAPTURE_ID)
--   (e) BUILD_PLAN(STUDENT_ID, CAPTURE_ID, EXTRA_CONTEXT)
--   (f) RECORD_ACTION(STUDENT_ID, PLAN_ID, TASK_ID, KIND)
--
-- The procedures are LANGUAGE JAVASCRIPT + EXECUTE AS CALLER: the caller's Cortex
-- privileges and session TIMEZONE apply, every SQL statement uses bind variables,
-- and each Cortex attempt is isolated in try/catch (a missing function only fails
-- that attempt). The pre-rank itself is one SQL query using the UDFs below.
-- =============================================================================

USE WAREHOUSE PIP_WH;
USE SCHEMA PIP.APP;

-- -----------------------------------------------------------------------------
-- (a) Cortex verification. Tries each function/model with a trivial prompt; the
-- first success wins. Result is MERGEd into CORTEX_CONFIG and returned.
-- AI_TRANSCRIBE is probed with a file that does not exist: "unknown function"
-- means unavailable, any other error (file not found, etc.) means the function
-- exists. The API /health?refresh=1 does the definitive check with a real m4a.
-- -----------------------------------------------------------------------------
EXECUTE IMMEDIATE
$$
DECLARE
  v_complete_fn    VARCHAR DEFAULT NULL;
  v_complete_model VARCHAR DEFAULT NULL;
  v_embed_fn       VARCHAR DEFAULT NULL;
  v_transcribe_fn  VARCHAR DEFAULT NULL;
  v_fn             VARCHAR;
  v_model          VARCHAR;
  v_sql            VARCHAR;
  v_msg            VARCHAR;
  v_errors         VARCHAR DEFAULT '';
BEGIN
  -- completion: AI_COMPLETE x 3 models, then SNOWFLAKE.CORTEX.COMPLETE x 3 models
  FOR i IN 0 TO 5 DO
    IF (v_complete_fn IS NULL) THEN
      IF (i < 3) THEN
        v_fn := 'AI_COMPLETE';
      ELSE
        v_fn := 'SNOWFLAKE.CORTEX.COMPLETE';
      END IF;
      IF (i = 0 OR i = 3) THEN
        v_model := 'claude-sonnet-4-5';
      ELSEIF (i = 1 OR i = 4) THEN
        v_model := 'mistral-large2';
      ELSE
        v_model := 'llama3.1-8b';
      END IF;
      v_sql := 'SELECT ' || v_fn || '(''' || v_model || ''', ''Reply with the single word OK.'')';
      BEGIN
        EXECUTE IMMEDIATE :v_sql;
        v_complete_fn := v_fn;
        v_complete_model := v_model;
      EXCEPTION
        WHEN OTHER THEN
          v_msg := SQLERRM;
          v_errors := v_errors || v_fn || '/' || v_model || ': ' || LEFT(v_msg, 200) || ' | ';
      END;
    END IF;
  END FOR;

  -- embeddings
  BEGIN
    EXECUTE IMMEDIATE 'SELECT AI_EMBED(''snowflake-arctic-embed-m-v1.5'', ''hello'')';
    v_embed_fn := 'AI_EMBED';
  EXCEPTION
    WHEN OTHER THEN
      v_msg := SQLERRM;
      v_errors := v_errors || 'AI_EMBED: ' || LEFT(v_msg, 200) || ' | ';
  END;
  IF (v_embed_fn IS NULL) THEN
    BEGIN
      EXECUTE IMMEDIATE 'SELECT SNOWFLAKE.CORTEX.EMBED_TEXT_768(''snowflake-arctic-embed-m-v1.5'', ''hello'')';
      v_embed_fn := 'SNOWFLAKE.CORTEX.EMBED_TEXT_768';
    EXCEPTION
      WHEN OTHER THEN
        v_msg := SQLERRM;
        v_errors := v_errors || 'EMBED_TEXT_768: ' || LEFT(v_msg, 200) || ' | ';
    END;
  END IF;

  -- transcription probe (a success is not expected: the file does not exist)
  BEGIN
    EXECUTE IMMEDIATE 'SELECT AI_TRANSCRIBE(TO_FILE(''@PIP.APP.AUDIO_STAGE'', ''pip_verify/does_not_exist.m4a''))';
    v_transcribe_fn := 'AI_TRANSCRIBE';
  EXCEPTION
    WHEN OTHER THEN
      v_msg := SQLERRM;
      IF (v_msg ILIKE '%unknown function%' OR v_msg ILIKE '%unknown user-defined function%' OR v_msg ILIKE '%invalid identifier%') THEN
        v_transcribe_fn := NULL;
        v_errors := v_errors || 'AI_TRANSCRIBE: ' || LEFT(v_msg, 200) || ' | ';
      ELSE
        v_transcribe_fn := 'AI_TRANSCRIBE';
      END IF;
  END;

  MERGE INTO PIP.APP.CORTEX_CONFIG t
  USING (
    SELECT 'complete_fn' AS cfg_key, :v_complete_fn AS cfg_value
    UNION ALL SELECT 'complete_model', :v_complete_model
    UNION ALL SELECT 'embed_fn', :v_embed_fn
    UNION ALL SELECT 'transcribe_fn', :v_transcribe_fn
  ) s
  ON t.key = s.cfg_key
  WHEN MATCHED THEN UPDATE SET value = s.cfg_value, verified_at = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
  WHEN NOT MATCHED THEN INSERT (key, value, verified_at)
    VALUES (s.cfg_key, s.cfg_value, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ);

  RETURN OBJECT_CONSTRUCT_KEEP_NULL(
    'complete_fn', v_complete_fn,
    'complete_model', v_complete_model,
    'embed_fn', v_embed_fn,
    'transcribe_fn', v_transcribe_fn,
    'errors', v_errors);
END;
$$;

SELECT * FROM PIP.APP.CORTEX_CONFIG ORDER BY key;

-- -----------------------------------------------------------------------------
-- (b) Helper UDFs
-- -----------------------------------------------------------------------------

-- LLM text -> JSON object. Code fences and prose are dropped by slicing from the
-- first '{' to the last '}'; returns NULL when nothing parses.
CREATE OR REPLACE FUNCTION PIP.APP.PIP_EXTRACT_JSON(S VARCHAR)
RETURNS VARIANT
AS
$$
  CASE
    WHEN S IS NULL THEN NULL
    WHEN POSITION('{', S) = 0 OR POSITION('}', REVERSE(S)) = 0 THEN NULL
    WHEN (LENGTH(S) - POSITION('}', REVERSE(S)) + 1) < POSITION('{', S) THEN NULL
    ELSE TRY_PARSE_JSON(
      SUBSTR(S, POSITION('{', S), (LENGTH(S) - POSITION('}', REVERSE(S)) + 1) - POSITION('{', S) + 1))
  END
$$;

-- Minutes of the first useful step (CONTRACT section 4).
CREATE OR REPLACE FUNCTION PIP.APP.PIP_FIRST_STEP_MINUTES(CATEGORY VARCHAR, EST_MINUTES NUMBER)
RETURNS NUMBER
AS
$$
  CASE
    WHEN CATEGORY IN ('assignment', 'work', 'class') THEN LEAST(COALESCE(EST_MINUTES, 60), 20)
    ELSE COALESCE(EST_MINUTES, 15)
  END
$$;

-- Relative cost (0..1) of postponing a task by T hours (CONTRACT section 4 curves).
-- Mirrors api/src/ranker/decay.ts: HOURS_TO_DUE is NULL for undated tasks (cliff then
-- falls back to linear), HOURS_OPEN is clamped at 0, a non-positive half-life counts
-- as 1 h, and the result is clamped to 0..1. Single SQL expression (UDF body rule).
CREATE OR REPLACE FUNCTION PIP.APP.PIP_DECAY_COST(
  CURVE VARCHAR, FLOOR_WEIGHT FLOAT, HALF_LIFE_HOURS FLOAT,
  HOURS_TO_DUE FLOAT, HOURS_OPEN FLOAT, DEFER_COUNT FLOAT, T FLOAT)
RETURNS FLOAT
AS
$$
  GREATEST(0.0, LEAST(1.0,
    CASE
      WHEN CURVE = 'cliff' AND HOURS_TO_DUE IS NOT NULL THEN
        IFF(HOURS_TO_DUE <= 0 OR T >= HOURS_TO_DUE, 1.0,
            FLOOR_WEIGHT + (0.5 - FLOOR_WEIGHT) * DIV0(T, HOURS_TO_DUE))
      WHEN CURVE = 'daily_reset' THEN
        FLOOR_WEIGHT + (1 - FLOOR_WEIGHT) * (MOD(GREATEST(COALESCE(HOURS_OPEN, 0), 0) + T, 24) / 24)
      WHEN CURVE = 'rising_floor' THEN
        FLOOR_WEIGHT + DIV0(GREATEST(COALESCE(HOURS_OPEN, 0), 0) + T,
                            2 * IFF(HALF_LIFE_HOURS > 0, HALF_LIFE_HOURS, 1))
      WHEN CURVE = 'defer_multiplier' THEN
        (FLOOR_WEIGHT + DIV0(T, 2 * IFF(HALF_LIFE_HOURS > 0, HALF_LIFE_HOURS, 1)))
          * (1 + 0.5 * COALESCE(DEFER_COUNT, 0))
      ELSE
        FLOOR_WEIGHT + DIV0(T, 2 * IFF(HALF_LIFE_HOURS > 0, HALF_LIFE_HOURS, 1))
    END))
$$;

-- TIMESTAMP_NTZ -> '2:00 PM'
CREATE OR REPLACE FUNCTION PIP.APP.PIP_FMT_TIME(TS TIMESTAMP_NTZ)
RETURNS VARCHAR
AS
$$
  IFF(MOD(HOUR(TS), 12) = 0, 12, MOD(HOUR(TS), 12))::VARCHAR
    || ':' || LPAD(MINUTE(TS)::VARCHAR, 2, '0')
    || IFF(HOUR(TS) < 12, ' AM', ' PM')
$$;
